---
authors: ["brice.dutheil"]
date: "2020-04-24T11:54:58+02:00"
language: en
draft: true
#tags: ["log","jvm","java","unified logging", "jep-158"]
slug: "exploring-jvm-unified-logs"
title: "Exploring JVM unified logs"
---

So you came this

https://github.com/corretto/corretto-11/blob/2750418af3603bcb10ba5e933a7198f21b78361d/src/src/hotspot/share/logging/logTag.hpp[src/hotspot/share/logging/logTag.hpp]


.Log tags
[]
|===

| add                   | Redefinition                   |
| age                   | GC                             |
| alloc                 | GC                             | GC region or space allocation
| annotation            | Redefinition                   |
| aot                   | AOT                            | Ahead of time logs
| arguments             |                                | JVM options warnings or errors
| attach                |                                | JVM attachment listener
| barrier               | GC,xxx                         | GC Write barrier coverage
| biasedlocking         |                                | Biased Locking mechanism https://github.com/corretto/corretto-11/blob/8bb50b6fcf0613dc85010c45f96fa048ecd5dba4/src/src/hotspot/share/runtime/biasedLocking.hpp[src/hotspot/share/runtime/biasedLocking.hpp]
| blocks                | OOP Strage, GC                 |
| bot                   | GC                             | Block Offset Table (side data structure with offset information indicating how far back the GC needs to go to find the beginning of an object).
| breakpoint            | JVMTI (Redefinition)           | Part of the JVMTI, but logged under `redefine` prefix.
| bytecode              | JFR                            |
| cds                   | Class Data sharing             | Class Data Sharing logs
| census                | GC                             | CMS log about `freelist` information.
| class                 | Classes,AOT                    | Class related information
| classhisto            | GC                             |
| cleanup               | Safe-points                    | Safepoint cleaning information
| codecache             | Code cache, Compilation        | code cache for generated code: compiled java methods, runtime stubs, transition frames, etc. Segregated in 3 heaps (Non-nmethods like Buffers, Adapters and Runtime Stubs, nmethods that are profiled, nmethods that are not profiled). https://github.com/corretto/corretto-11/blob/2b351313740f148597cf680d8443df93931de813/src/src/hotspot/share/code/codeCache.cpp[src/hotspot/share/code/codeCache.cpp]
| compaction            | GC                             | GC compaction for G1GC and Parallel
| compilation           | Compilation, jit               | Compilation
| constantpool          | Classes,Redefinition           | Constant pool, logged mostly during `redefine`
| constraints           | Classes                        | Class loader constraints
| container             | OS                             | Container (CGroup) related (`cpu`, `cpuset`, `memory`, `mountinfo`, ...)
| coops                 | GC                             | Compressed ordinary object pointers
| cpu                   | GC,OS                          | CPU features when logged with `os`, CPU time ith `gc`
| cset                  | GC                             | Collection Set in G1
| data                  | Classes                        | Classloader data (allocation space, or metaspace)
| datacreation          | perf                           | Related to perf data creation
| dcmd                  | JFR                            | Diagnostic command, apparently only prefixed by `jfr`
| decoder               |                                | Related to ELF decoding (Executable and Linkable Format)
| defaultmethods        |                                | Runtime support for default method. Part of classes, but logged as a standalone tag.
| director              | GC                             | Related to ZGC
| dump                  | Redefinition                   |
| ergo                  | GC                             | Ergonomics, usually prefixes by `gc`, but can be found alone (e.g. for 2 logs about thread local handshakes)
| event                 | JFR                            | About JFR events
| exceptions            |                                | About Java exceptions handling in different parts (interpreter, during safepoint, compiler, ...). Specific exception handling during redefinition when prefixed by `redefine`.
| exit                  | GC                             | GC/heap related information after GC. `LogStreamHandle(Debug, gc, heap, exit) lsh;` https://github.com/corretto/corretto-11/blob/caa2f4cad666b508a88b92db01054ace8647a820/src/src/hotspot/share/gc/shared/genCollectedHeap.cpp[src/hotspot/share/gc/shared/genCollectedHeap.cpp]
| fingerprint           | Classes,AOT                    | Class fingerprinting
| free                  | malloc                         | Log any C stdlib `malloc`, `realloc` or `free` calls, always logged via `malloc, free` tags.
| freelist              | GC                             | Chunks of memory that are supposed to be free, for CMS and metaspace
| gc                    | GC                             | GC log prefix
| handshake             | Threads                        | Thread local handshakes https://github.com/corretto/corretto-11/blob/8bb50b6fcf0613dc85010c45f96fa048ecd5dba4/src/src/hotspot/share/runtime/handshake.hpp#L35-L39[src/hotspot/share/runtime/handshake.hpp]
| hashtables            |                                | When standalone, it's the internal bucketed hash table, far cousin of a `HashMap`, Hotspot uses it for strings, and other symbols. CDS uses another internal implementation for statistics, hence this tag may be prefixed by `cds`.
| heap                  | GC                             | Various GC heap related logs
| humongous             | GC                             | Humongous objects in G1GC
| ihop                  | GC                             | Heap occupancy (initial, current, target) in G1GC
| iklass                | Classes,Redefinition           | Internal class instance representation, logged prefixes `redefine`, `classes`
| init                  | GC,Classes                     | Mostly about class initialization when prefixed by `class`. About ZGC initialization when prefixed by `gc`.
| inlining              | jit                            | Method inlining information
| interpreter           | interpreter                    | Interpreter logs, only logs with `oopmap` and `safepoint` sub-tags.
| itables               |                                | Log interface calls, during JVM development (non-product build needed).
| jfr                   | JFR                            | JDK Flight Recorder
| jit                   | jit                            | Logs about method `inlining` and `compilation`
| jni                   | GC                             | Only logged during _GC locker_.
| jvmti                 | JVMTI                          |
| liveness              | GC                             | G1GC region liveness (dead objects vs live objects)
| load                  | GC,Classes                     | Trace all classes loaded
| loader                | Classes                        | Class loader `data` and `constraints`
| logging               |                                | About unified logging
| malloc                | malloc                         | Log any C stdlib `malloc`, `realloc` or `free` calls, always logged via `malloc, free` tags.
| mark                  | Redefinition                   | Mark `obsolete` method during `redefine`
| marking               | GC                             | Marking information for G1GC, CMS, ZGC
| membername            | (Redefinition)                 | Hashtable used by redefinition to replace methods. Used in conjunction with `table`, but without `redefine` prefix.
| memops                | perf                           | Memory operation logs `initialize` and `mmap_attach_shared`
| metadata              | JFR,Redefinition               | Logs about class redefinition, or logs about JFR metadata (although I didn't found any jfr logs in the codebase)
| metaspace             | GC                             | Logs about the metaspace memory space
| methodcomparator      | redefinition                   | Logs about method equivalence during redefinition.
| mirror                | CDS                            | Logs about `cds` processing of class mirror. A java mirror is an instance of a `java.lang.Class`.
| mmu                   | GC                             | _Minimum Mutator Utilization_ is the (time) goal of GC work for G1GC and ZGC. G1GC defines this as a pause time goal (`MaxGCPauseMillis`) over a time slice (`GCPauseIntervalMillis`).
| module                |                                | Module system
| monitorinflation      |                                | Runtime synchronization support
| monitormismatch       |                                | Monitor matching failures during OopMapGeneration
| nestmates             | Classes                        | Nestmate logging
| nmethod               | GC,Classes,Redefinition        | native methods (as in compiled code versions of Java methods) logs in various subsystems: `gc`, `class`, `redefine`
| normalize             | Redefinition                   | Logs after method addition,deletion,replacement during redefinition
| objecttagging         | JVMTI                          | JVMTI object tagging calls
| obsolete              | Redefinition                   | Obsolete method entry mainly for redefinition (and JVMTI)
| oldobject             | jfr                            | Old object sampling, currently only logging that sample was skipped due to lock contention.
| oom                   | gc                             | Reported when `metaspace` is out of memory.
| oopmap                | interpreter, redefinition      | Ordinary Object Pointer caching logs, prefixed by `interpreter` and `redefine`.
| oops                  | gc                             | Ordinary Object Pointers logs in CMS and ZGC
| oopstorage            |                                | Internal off-heap data structure for management of references to objects allocated in the Java heap
| os                    | OS                             | Operating System interactions logs.
| pagesize              |                                | Logs about page size. Not prefixed by `os`.
| parser                | JFR                            | Part of jfr, but log instructions found in the code base.
| patch                 | module                         | Logging `--patch-module`
| path                  | Classes                        | Class path or module path processing
| perf                  | perf                           | Logs about JVM perf counters, when prefixed by `stringtable` it's about interned strings (`String.intern()`).
| phases                | GC                             | Logs that is part of phase of a GC, in particular for ZGC and G1GC.
| plab                  | GC                             | Logs about per-GC-thread allocation buffer, those are used during GC to prevent thread competition on the same memory space.
| preorder              | Classes                        | Trace all classes loaded in order referenced (not loaded)
| preview               |                                | Trace loading of preview feature types
| promotion             | GC                             | Object promotion logs during GC.
| protectiondomain      | Classes                        | Class protection domain verification.
| purge                 | Redefinition                   |
| redefine              | Redefinition                   |
| ref                   | GC                             |
| refine                | GC                             |
| region                | GC                             |
| reloc                 | GC                             |
| remset                | GC                             |
| resolve               | Classes,AOT                    |
| safepoint             | Safe-points                    |
| sampling              |                                |
| scavenge              | GC                             |
| setting               | JFR                            |
| smr                   |                                |
| stackmap              |                                |
| stacktrace            |                                |
| stackwalk             |                                |
| start                 |                                |
| startuptime           | GC,AOT,xxx                     |
| state                 |                                |
| stats                 | GC,xxx                         |
| stringdedup           | GC                             |
| stringtable           | GC                             |
| subclass              |                                |
| survivor              | GC                             |
| sweep                 | Code cache                     |
| system                | JFR                            |
| table                 | membername                     | Only used with `membername`, about the hashtable to record methods, and replace them during redefinition.
| task                  | GC,xxx                         |
| thread                |                                |
| time                  | GC                             |
| timer                 |                                |
| tlab                  | GC                             |
| tracking              | GC,xxx                         |
| unload                | Classes                        |
| unshareable           | CDS                            |
| update                |                                |
| verification          |                                |
| verify                | GC                             |
| vmoperation           |                                |
| vmthread              |                                |
| vtables               |                                |
| vtablestubs           |                                |
| workgang              | GC                             |

|===

.JFR prefixes https://github.com/corretto/corretto-11/blob/8bb50b6fcf0613dc85010c45f96fa048ecd5dba4/src/src/hotspot/share/jfr/utilities/jfrLogTagSets.hpp[src/hotspot/share/jfr/utilities/jfrLogTagSets.hpp]
[source, c++]
----
#define JFR_LOG_TAG_SET_LIST \
  JFR_LOG_TAG(jfr) \
  JFR_LOG_TAG(jfr, system) \
  JFR_LOG_TAG(jfr, system, event) \
  JFR_LOG_TAG(jfr, system, setting) \
  JFR_LOG_TAG(jfr, system, bytecode) \
  JFR_LOG_TAG(jfr, system, parser) \
  JFR_LOG_TAG(jfr, system, metadata) \
  JFR_LOG_TAG(jfr, metadata) \
  JFR_LOG_TAG(jfr, event) \
  JFR_LOG_TAG(jfr, setting) \
  JFR_LOG_TAG(jfr, dcmd)
  /* NEW TAGS, DONT FORGET TO UPDATE JAVA SIDE */
----

.CG prefixes https://github.com/corretto/corretto-11/blob/8bb50b6fcf0613dc85010c45f96fa048ecd5dba4/src/src/hotspot/share/logging/logPrefix.hpp#L45-L90[src/hotspot/share/logging/logPrefix.hpp#L45-L90]
[source, cpp]
----
#define LOG_PREFIX_LIST \
  LOG_PREFIX(GCId::print_prefix, LOG_TAGS(gc)) \
  LOG_PREFIX(GCId::print_prefix, LOG_TAGS(gc, age)) \
  LOG_PREFIX(GCId::print_prefix, LOG_TAGS(gc, alloc)) \
  LOG_PREFIX(GCId::print_prefix, LOG_TAGS(gc, alloc, region)) \
  LOG_PREFIX(GCId::print_prefix, LOG_TAGS(gc, barrier)) \
  LOG_PREFIX(GCId::print_prefix, LOG_TAGS(gc, classhisto)) \
  LOG_PREFIX(GCId::print_prefix, LOG_TAGS(gc, compaction)) \
  LOG_PREFIX(GCId::print_prefix, LOG_TAGS(gc, cpu)) \
  LOG_PREFIX(GCId::print_prefix, LOG_TAGS(gc, ergo)) \
  LOG_PREFIX(GCId::print_prefix, LOG_TAGS(gc, ergo, cset)) \
  LOG_PREFIX(GCId::print_prefix, LOG_TAGS(gc, ergo, heap)) \
  LOG_PREFIX(GCId::print_prefix, LOG_TAGS(gc, ergo, ihop)) \
  LOG_PREFIX(GCId::print_prefix, LOG_TAGS(gc, ergo, refine)) \
  LOG_PREFIX(GCId::print_prefix, LOG_TAGS(gc, heap)) \
  LOG_PREFIX(GCId::print_prefix, LOG_TAGS(gc, heap, region)) \
  LOG_PREFIX(GCId::print_prefix, LOG_TAGS(gc, freelist)) \
  LOG_PREFIX(GCId::print_prefix, LOG_TAGS(gc, humongous)) \
  LOG_PREFIX(GCId::print_prefix, LOG_TAGS(gc, ihop)) \
  LOG_PREFIX(GCId::print_prefix, LOG_TAGS(gc, liveness)) \
  LOG_PREFIX(GCId::print_prefix, LOG_TAGS(gc, load)) \
  LOG_PREFIX(GCId::print_prefix, LOG_TAGS(gc, marking)) \
  LOG_PREFIX(GCId::print_prefix, LOG_TAGS(gc, metaspace)) \
  LOG_PREFIX(GCId::print_prefix, LOG_TAGS(gc, mmu)) \
  LOG_PREFIX(GCId::print_prefix, LOG_TAGS(gc, nmethod)) \
  LOG_PREFIX(GCId::print_prefix, LOG_TAGS(gc, phases)) \
  LOG_PREFIX(GCId::print_prefix, LOG_TAGS(gc, phases, ref)) \
  LOG_PREFIX(GCId::print_prefix, LOG_TAGS(gc, phases, start)) \
  LOG_PREFIX(GCId::print_prefix, LOG_TAGS(gc, phases, task)) \
  LOG_PREFIX(GCId::print_prefix, LOG_TAGS(gc, plab)) \
  LOG_PREFIX(GCId::print_prefix, LOG_TAGS(gc, region)) \
  LOG_PREFIX(GCId::print_prefix, LOG_TAGS(gc, remset)) \
  LOG_PREFIX(GCId::print_prefix, LOG_TAGS(gc, remset, tracking)) \
  LOG_PREFIX(GCId::print_prefix, LOG_TAGS(gc, ref)) \
  LOG_PREFIX(GCId::print_prefix, LOG_TAGS(gc, ref, start)) \
  LOG_PREFIX(GCId::print_prefix, LOG_TAGS(gc, reloc)) \
  LOG_PREFIX(GCId::print_prefix, LOG_TAGS(gc, start)) \
  LOG_PREFIX(GCId::print_prefix, LOG_TAGS(gc, stringtable)) \
  LOG_PREFIX(GCId::print_prefix, LOG_TAGS(gc, sweep)) \
  LOG_PREFIX(GCId::print_prefix, LOG_TAGS(gc, task)) \
  LOG_PREFIX(GCId::print_prefix, LOG_TAGS(gc, task, start)) \
  LOG_PREFIX(GCId::print_prefix, LOG_TAGS(gc, task, stats)) \
  LOG_PREFIX(GCId::print_prefix, LOG_TAGS(gc, task, time)) \
  DEBUG_ONLY(LOG_PREFIX(Test_log_prefix_prefixer, LOG_TAGS(logging, test))) \
  LOG_PREFIX(GCId::print_prefix, LOG_TAGS(gc, tlab)) \
  LOG_PREFIX(GCId::print_prefix, LOG_TAGS(gc, workgang))
----


.AOT https://github.com/corretto/corretto-11/blob/2b351313740f148597cf680d8443df93931de813/src/src/hotspot/share/aot/aotCodeHeap.cpp[src/hotspot/share/aot/aotCodeHeap.cpp]
* `log_debug(aot, class, resolve)`
* `log_info(aot, class, resolve)`
* `log_trace(aot, class, fingerprint)`
* `log_trace(aot, class, load)`


.Classes
* classfile
** `log_error(class)` https://github.com/corretto/corretto-11/blob/caa2f4cad666b508a88b92db01054ace8647a820/src/src/hotspot/share/classfile/javaClasses.cpp[src/hotspot/share/classfile/javaClasses.cpp]
** `log_info(class, fingerprint)` https://github.com/corretto/corretto-11/blob/2b351313740f148597cf680d8443df93931de813/src/src/hotspot/share/classfile/classFileParser.cpp[src/hotspot/share/classfile/classFileParser.cpp]
** `log_info(class, preview)` https://github.com/corretto/corretto-11/blob/2b351313740f148597cf680d8443df93931de813/src/src/hotspot/share/classfile/classFileParser.cpp[src/hotspot/share/classfile/classFileParser.cpp]
** `log_debug(class, resolve)` https://github.com/corretto/corretto-11/blob/2b351313740f148597cf680d8443df93931de813/src/src/hotspot/share/classfile/classFileParser.cpp[src/hotspot/share/classfile/classFileParser.cpp]

** `LogMessage(class, load)` https://github.com/corretto/corretto-11/blob/caa2f4cad666b508a88b92db01054ace8647a820/src/src/hotspot/share/oops/instanceKlass.cpp[src/hotspot/share/oops/instanceKlass.cpp]
** `log_trace(class, nestmates)` https://github.com/corretto/corretto-11/blob/caa2f4cad666b508a88b92db01054ace8647a820/src/src/hotspot/share/oops/instanceKlass.cpp[src/hotspot/share/oops/instanceKlass.cpp]
** `LogTarget(Info, class, init)` https://github.com/corretto/corretto-11/blob/caa2f4cad666b508a88b92db01054ace8647a820/src/src/hotspot/share/oops/instanceKlass.cpp[src/hotspot/share/oops/instanceKlass.cpp]
** `log_trace(class, fingerprint)` https://github.com/corretto/corretto-11/blob/caa2f4cad666b508a88b92db01054ace8647a820/src/src/hotspot/share/oops/instanceKlass.cpp[src/hotspot/share/oops/instanceKlass.cpp]

** `LogTarget(Debug, class, loader, data)` https://github.com/corretto/corretto-11/blob/caa2f4cad666b508a88b92db01054ace8647a820/src/src/hotspot/share/classfile/classLoaderData.cpp[src/hotspot/share/classfile/classLoaderData.cpp]
** `LogTarget(Trace, class, loader, data)` https://github.com/corretto/corretto-11/blob/caa2f4cad666b508a88b92db01054ace8647a820/src/src/hotspot/share/classfile/classLoaderData.cpp[src/hotspot/share/classfile/classLoaderData.cpp]
** `log_debug(class, loader, data)` https://github.com/corretto/corretto-11/blob/caa2f4cad666b508a88b92db01054ace8647a820/src/src/hotspot/share/classfile/classLoaderData.cpp[src/hotspot/share/classfile/classLoaderData.cpp]

** `log_info(class, load)` https://github.com/corretto/corretto-11/blob/0fb85ec862711e6daa4db7d7fab819c0e7a1273d/src/src/hotspot/share/classfile/classLoader.cpp[src/hotspot/share/classfile/classLoader.cpp]
** `log_info(class, path)` https://github.com/corretto/corretto-11/blob/0fb85ec862711e6daa4db7d7fab819c0e7a1273d/src/src/hotspot/share/classfile/classLoader.cpp[src/hotspot/share/classfile/classLoader.cpp]

** `LogTarget(Info, class, loader, constraints)` https://github.com/corretto/corretto-11/blob/8bb50b6fcf0613dc85010c45f96fa048ecd5dba4/src/src/hotspot/share/classfile/loaderConstraints.cpp[src/hotspot/share/classfile/loaderConstraints.cpp]

** `log_debug(class, init)` https://github.com/corretto/corretto-11/blob/2b351313740f148597cf680d8443df93931de813/src/src/hotspot/share/classfile/verifier.cpp[src/hotspot/share/classfile/verifier.cpp]
** `log_debug(class, resolve)` https://github.com/corretto/corretto-11/blob/2b351313740f148597cf680d8443df93931de813/src/src/hotspot/share/classfile/verifier.cpp[src/hotspot/share/classfile/verifier.cpp]
** `log_info(verification)` https://github.com/corretto/corretto-11/blob/2b351313740f148597cf680d8443df93931de813/src/src/hotspot/share/classfile/verifier.cpp[src/hotspot/share/classfile/verifier.cpp]

* Class loding service
** `log_info(class, unload)` https://github.com/corretto/corretto-11/blob/8bb50b6fcf0613dc85010c45f96fa048ecd5dba4/src/src/hotspot/share/services/classLoadingService.cpp[src/hotspot/share/services/classLoadingService.cpp]

* Constant Pool
** `log_debug(class, resolve)` https://github.com/corretto/corretto-11/blob/2b351313740f148597cf680d8443df93931de813/src/src/hotspot/share/oops/constantPool.cpp[src/hotspot/share/oops/constantPool.cpp]

* Native methods (compiled code versions of Java methods)
** `LogTarget(Trace, class, unload, nmethod)` https://github.com/corretto/corretto-11/blob/caa2f4cad666b508a88b92db01054ace8647a820/src/src/hotspot/share/code/nmethod.cpp[src/hotspot/share/code/nmethod.cpp]

* Memory
** `log_info(class, path)` https://github.com/corretto/corretto-11/blob/6887ddf929a1baae5b4f73a3b6c255c4ee942f7c/src/src/hotspot/share/memory/filemap.cpp[src/hotspot/share/memory/filemap.cpp]

* OOPS
** `log_trace(class, unload)` https://github.com/corretto/corretto-11/blob/2b351313740f148597cf680d8443df93931de813/src/src/hotspot/share/oops/klass.cpp[src/hotspot/share/oops/klass.cpp]

* JNI
** `log_is_enabled(Debug, class, resolve)` https://github.com/corretto/corretto-11/blob/caa2f4cad666b508a88b92db01054ace8647a820/src/src/hotspot/share/prims/jni.cpp[src/hotspot/share/prims/jni.cpp]
+
`log_debug(class, resolve)` https://github.com/corretto/corretto-11/blob/2b351313740f148597cf680d8443df93931de813/src/src/hotspot/share/prims/jvm.cpp[src/hotspot/share/prims/jvm.cpp]

* Reflection
** `log_debug(class, resolve)` https://github.com/corretto/corretto-11/blob/caa2f4cad666b508a88b92db01054ace8647a820/src/src/hotspot/share/runtime/reflection.cpp[src/hotspot/share/runtime/reflection.cpp]


.Class Data Sharing
* `log_info(cds)` https://github.com/corretto/corretto-11/blob/6887ddf929a1baae5b4f73a3b6c255c4ee942f7c/src/src/hotspot/share/memory/filemap.cpp[src/hotspot/share/memory/filemap.cpp]
* `log_trace(cds)` https://github.com/corretto/corretto-11/blob/2b351313740f148597cf680d8443df93931de813/src/src/hotspot/share/oops/klass.cpp[src/hotspot/share/oops/klass.cpp]
* `log_trace(cds, unshareable)` https://github.com/corretto/corretto-11/blob/2b351313740f148597cf680d8443df93931de813/src/src/hotspot/share/oops/klass.cpp[src/hotspot/share/oops/klass.cpp]
* `log_debug(cds, mirror)` https://github.com/corretto/corretto-11/blob/2b351313740f148597cf680d8443df93931de813/src/src/hotspot/share/oops/klass.cpp[src/hotspot/share/oops/klass.cpp]
* `log_trace(cds)` https://github.com/corretto/corretto-11/blob/2b351313740f148597cf680d8443df93931de813/src/src/hotspot/share/oops/constantPool.cpp[src/hotspot/share/oops/constantPool.cpp]

.Redefine
* Native methods (compiled code versions of Java methods)
** `log_debug(redefine, class, nmethod)` https://github.com/corretto/corretto-11/blob/caa2f4cad666b508a88b92db01054ace8647a820/src/src/hotspot/share/code/nmethod.cpp[src/hotspot/share/code/nmethod.cpp]

* Interpreter
** `log_debug(redefine, class, interpreter, oopmap)` https://github.com/corretto/corretto-11/blob/8bb50b6fcf0613dc85010c45f96fa048ecd5dba4/src/src/hotspot/share/interpreter/oopMapCache.cpp[src/hotspot/share/interpreter/oopMapCache.cpp]


.Compilation, Just-in-Time
* `Log(compilation, codecache) log; if(log.is_debug())`  https://github.com/corretto/corretto-11/blob/caa2f4cad666b508a88b92db01054ace8647a820/src/src/hotspot/share/compiler/compileBroker.cpp[src/hotspot/share/compiler/compileBroker.cpp]
* `LogTarget(Debug, jit, compilation)` https://github.com/corretto/corretto-11/blob/2b351313740f148597cf680d8443df93931de813/src/src/hotspot/share/compiler/compileTask.cpp[src/hotspot/share/compiler/compileTask.cpp]
* ``
* ``

* `log_debug(interpreter, oopmap)` https://github.com/corretto/corretto-11/blob/8bb50b6fcf0613dc85010c45f96fa048ecd5dba4/src/src/hotspot/share/interpreter/oopMapCache.cpp[src/hotspot/share/interpreter/oopMapCache.cpp]


.Java Virtual Machine Tool Interface (JVMTI, JSR-163)


== JEP-158 : Unified JVM Logging

https://openjdk.java.net/jeps/158

.syntax
[source]
----
-Xlog[:option]
    option         :=  [<what>][:[<output>][:[<decorators>][:<output-options>]]]
                       'help'
                       'disable'
    what           :=  <selector>[,...]
    selector       :=  <tag-set>[*][=<level>]
    tag-set        :=  <tag>[+...]
                       'all'
    tag            :=  name of tag
    level          :=  trace
                       debug
                       info
                       warning
                       error
    output         :=  'stderr'
                       'stdout'
                       [file=]<filename>
    decorators     :=  <decorator>[,...]
                       'none'
    decorator      :=  time
                       uptime
                       timemillis
                       uptimemillis
                       timenanos
                       uptimenanos
                       pid
                       tid
                       level
                       tags
    output-options :=  <output_option>[,...]
    output-option  :=  filecount=<file count>
                       filesize=<file size>
                       parameter=value
----


.In the JVM codebase
____
*JVM interface*

In the JVM a set of macros will be created with an API similar to:

[source]
----
log_<level>(Tag1[,...])(fmtstr, ...)
    syntax for the log macro
----

*Example:*

[source]
----
log_info(gc, rt, classloading)("Loaded %d objects.", object_count)
    the macro is checking the log level to avoid uneccessary
    calls and allocations.

log_debug(svc, debugger)("Debugger interface listening at port %d.", port_number)
----

____


.A note about `jcmd`
____
*Controlling at runtime*

Logging can be controlled at runtime through Diagnostic Commands (the `jcmd` utility).
Everything that can be specified on the command line can also be specified dynamically
with Diagnostic Commands. Since diagnostic commands are automatically exposed as MBeans
it will be possible to use JMX to change logging configuration in runtime.

____


=== How to use the tool, help from the command line

.`java` command
[source,role="primary"]
----
$ java -Xlog:help
Picked up JAVA_TOOL_OPTIONS:
-Xlog Usage: -Xlog[:[selections][:[output][:[decorators][:output-options]]]]
         where 'selections' are combinations of tags and levels of the form tag1[+tag2...][*][=level][,...]
         NOTE: Unless wildcard (*) is specified, only log messages tagged with exactly the tags specified will be matched.

Available log levels:
 off, trace, debug, info, warning, error

Available log decorators:
 time (t), utctime (utc), uptime (u), timemillis (tm), uptimemillis (um), timenanos (tn), uptimenanos (un), hostname (hn), pid (p), tid (ti), level (l), tags (tg)
 Decorators can also be specified as 'none' for no decoration.

Available log tags:
 add, age, alloc, annotation, aot, arguments, attach, barrier, biasedlocking, blocks, bot, breakpoint, bytecode, cds, census, class, classhisto, cleanup, codecache, compaction, compilation, constantpool, constraints, container, coops, cpu, cset, data, datacreation, dcmd, decoder, defaultmethods, director, dump, ergo, event, exceptions, exit, fingerprint, free, freelist, gc, handshake, hashtables, heap, humongous, ihop, iklass, init, inlining, interpreter, itables, jfr, jit, jni, jvmti, liveness, load, loader, logging, malloc, mark, marking, membername, memops, metadata, metaspace, methodcomparator, mirror, mmu, module, monitorinflation, monitormismatch, nestmates, nmethod, normalize, objecttagging, obsolete, oldobject, oom, oopmap, oops, oopstorage, os, pagesize, parser, patch, path, perf, phases, plab, preorder, preview, promotion, protectiondomain, purge, redefine, ref, refine, region, reloc, remset, resolve, safepoint, sampling, scavenge, setting, smr, stackmap, stacktrace, stackwalk, start, startuptime, state, stats, stringdedup, stringtable, subclass, survivor, sweep, system, table, task, thread, time, timer, tlab, tracking, unload, unshareable, update, verification, verify, vmoperation, vmthread, vtables, vtablestubs, workgang
 Specifying 'all' instead of a tag combination matches all tag combinations.

Described tag sets:
 logging: Logging for the log framework itself

Available log outputs:
 stdout/stderr
 file=<filename>
  If the filename contains %p and/or %t, they will expand to the JVM's PID and startup timestamp, respectively.
  Additional output-options for file outputs:
   filesize=..  - Target byte size for log rotation (supports K/M/G suffix). If set to 0, log rotation will not trigger automatically, but can be performed manually (see the VM.log DCMD).
   filecount=.. - Number of files to keep in rotation (not counting the active file). If set to 0, log rotation is disabled. This will cause existing log files to be overwritten.

Some examples:
 -Xlog
         Log all messages up to 'info' level to stdout with 'uptime', 'levels' and 'tags' decorations.
         (Equivalent to -Xlog:all=info:stdout:uptime,levels,tags).

 -Xlog:gc
         Log messages tagged with 'gc' tag up to 'info' level to stdout, with default decorations.

 -Xlog:gc,safepoint
         Log messages tagged either with 'gc' or 'safepoint' tags, both up to 'info' level, to stdout, with default decorations.
         (Messages tagged with both 'gc' and 'safepoint' will not be logged.)

 -Xlog:gc+ref=debug
         Log messages tagged with both 'gc' and 'ref' tags, up to 'debug' level, to stdout, with default decorations.
         (Messages tagged only with one of the two tags will not be logged.)

 -Xlog:gc=debug:file=gc.txt:none
         Log messages tagged with 'gc' tag up to 'debug' level to file 'gc.txt' with no decorations.

 -Xlog:gc=trace:file=gctrace.txt:uptimemillis,pid:filecount=5,filesize=1m
         Log messages tagged with 'gc' tag up to 'trace' level to a rotating fileset of 5 files of size 1MB,
         using the base name 'gctrace.txt', with 'uptimemillis' and 'pid' decorations.

 -Xlog:gc::uptime,tid
         Log messages tagged with 'gc' tag up to 'info' level to output 'stdout', using 'uptime' and 'tid' decorations.

 -Xlog:gc*=info,safepoint*=off
         Log messages tagged with at least 'gc' up to 'info' level, but turn off logging of messages tagged with 'safepoint'.
         (Messages tagged with both 'gc' and 'safepoint' will not be logged.)

 -Xlog:disable -Xlog:safepoint=trace:safepointtrace.txt
         Turn off all logging, including warnings and errors,
         and then enable messages tagged with 'safepoint' up to 'trace' level to file 'safepointtrace.txt'.
----

.`jcmd` command
[source,role="secondary"]
----
$ jcmd $(pidof java) help VM.log
6:
VM.log
Lists current log configuration, enables/disables/configures a log output, or rotates all logs.

Impact: Low: No impact

Permission: java.lang.management.ManagementPermission(control)

Syntax : VM.log [options]

Options: (options must be specified using the <key> or <key>=<value> syntax)
        output : [optional] The name or index (#<index>) of output to configure. (STRING, no default value)
        output_options : [optional] Options for the output. (STRING, no default value)
        what : [optional] Configures what tags to log. (STRING, no default value)
        decorators : [optional] Configures which decorators to use. Use 'none' or an empty value to remove all. (STRING, no default value)
        disable : [optional] Turns off all logging and clears the log configuration. (BOOLEAN, no default value)
        list : [optional] Lists current log configuration. (BOOLEAN, no default value)
        rotate : [optional] Rotates all logs. (BOOLEAN, no default value)

----

=== Configuring unified logging

From the help and the JEP above here's what to retain :


Tags::
When a log message is shown, it should be associated with a set of tags in the JVM which identify by names: `os`, `gc`, `modules`…

– We can apply different settings for individual tags.
– `\*` denotes _wildcard_ tag match. Not using `*` means all messages matching exactly the specified tags.

Levels::
We can perform logging at different levels. The available levels are `error`, `warning`, `info`, `debug`, `trace` and `develop`.

To disable logging, use the alternative `off`.

Outputs::
The output currently supports 3 types: stdout, stderr, or a text file, which can be set up for log file rotation based on written size and a number of files to rotate (for example: each 10MB, keep 5 files in rotation)

Decorators::
There are more details about the message called decorators. Here is the list:

* `time`/`timemillis`/`timenanos`: current time and date (ISO-8601 format)
* `uptime`/`uptimemillis`/`uptimenanos`: time since the start of the JVM
* `pid`: process identifier
* `tid`: thread identifier
* `level`: level associated with the log message
* `tags`: tag associated with the log message

Default settings::
.. tag-set: `all`.
.. level: `info`
.. output: `stdout`
.. decorators: `uptime`, `level`, `tags`


.`java` command
[source,role="primary"]
----
-Xlog:pagesize,os*,os+container=trace:file=/var/log/%t-os-container-pagezise.log:uptime,tags,level
----


.`jcmd` command
[source,role"secondary"]
----
$ jcmd 6 VM.log output=/var/log/%t-os-container-pagezise.log what=pagesize,os*,os+container=trace decorators=uptime,tags,level
----

The above commands are equivalent, but note that depending on the specified tags, the log content
may be less useful when enabled at a later time. And indeed in the above example, the `os+container=trace`
will output logs only during JVM bootstrap.

=== Interesting tags combinations

==== os and container

.output
[source]
----
$ head -n 200 /gclogs/2020-05-22_22-28-32-os-container-pagezise.log
[0.003s][trace][os,container] OSContainer::init: Initializing Container Support
[0.003s][trace][os,container] Path to /memory.use_hierarchy is /sys/fs/cgroup/memory/memory.use_hierarchy
[0.003s][trace][os,container] Use Hierarchy is: 1
[0.003s][trace][os,container] Path to /memory.limit_in_bytes is /sys/fs/cgroup/memory/memory.limit_in_bytes
[0.003s][trace][os,container] Memory Limit is: 5368709120
[0.003s][info ][os,container] Memory Limit is: 5368709120
[0.003s][trace][os,container] Path to /cpu.cfs_quota_us is /sys/fs/cgroup/cpu/cpu.cfs_quota_us
[0.003s][trace][os,container] CPU Quota is: -1
[0.003s][trace][os,container] Path to /cpu.cfs_period_us is /sys/fs/cgroup/cpu/cpu.cfs_period_us
[0.003s][trace][os,container] CPU Period is: 100000
[0.003s][trace][os,container] Path to /cpu.shares is /sys/fs/cgroup/cpu/cpu.shares
[0.004s][trace][os,container] CPU Shares is: 1024
[0.004s][trace][os,container] OSContainer::active_processor_count: 4
[0.004s][trace][os,container] Path to /cpu.cfs_quota_us is /sys/fs/cgroup/cpu/cpu.cfs_quota_us
[0.004s][trace][os,container] CPU Quota is: -1
[0.004s][trace][os,container] Path to /cpu.cfs_period_us is /sys/fs/cgroup/cpu/cpu.cfs_period_us
[0.004s][trace][os,container] CPU Period is: 100000
[0.004s][trace][os,container] Path to /cpu.shares is /sys/fs/cgroup/cpu/cpu.shares
[0.004s][trace][os,container] CPU Shares is: 1024
[0.004s][trace][os,container] OSContainer::active_processor_count: 4
[0.004s][info ][os          ] Use of CLOCK_MONOTONIC is supported
[0.004s][info ][os          ] Use of pthread_condattr_setclock is supported
[0.004s][info ][os          ] Relative timed-wait using pthread_cond_timedwait is associated with CLOCK_MONOTONIC
[0.004s][info ][os          ] HotSpot is running with glibc 2.28, NPTL 2.28
[0.005s][info ][os          ] SafePoint Polling address, bad (protected) page:0x00007fa25e8ee000, good (unprotected) page:0x00007fa25e8ef000
[0.005s][info ][os          ] attempting shared library load of /usr/lib/jvm/java-11-amazon-corretto/lib/libinstrument.so
[0.005s][info ][os          ] shared library load of /usr/lib/jvm/java-11-amazon-corretto/lib/libinstrument.so was successful
[0.005s][info ][os          ] attempting shared library load of /usr/lib/jvm/java-11-amazon-corretto/lib/libinstrument.so
[0.005s][info ][os          ] shared library load of /usr/lib/jvm/java-11-amazon-corretto/lib/libinstrument.so was successful
[0.006s][info ][os          ] attempting shared library load of /usr/lib/jvm/java-11-amazon-corretto/lib/libinstrument.so
[0.006s][info ][os          ] shared library load of /usr/lib/jvm/java-11-amazon-corretto/lib/libinstrument.so was successful
[0.008s][info ][os,thread   ] Thread attached (tid: 8, pthread id: 140335320479488).
[0.008s][info ][os          ] attempting shared library load of /usr/lib/jvm/java-11-amazon-corretto/lib/libzip.so
[0.008s][info ][os          ] shared library load of /usr/lib/jvm/java-11-amazon-corretto/lib/libzip.so was successful
[0.008s][info ][os          ] attempting shared library load of /usr/lib/jvm/java-11-amazon-corretto/lib/libjimage.so
[0.008s][info ][os          ] shared library load of /usr/lib/jvm/java-11-amazon-corretto/lib/libjimage.so was successful
[0.008s][trace][os,container] Path to /cpu.cfs_quota_us is /sys/fs/cgroup/cpu/cpu.cfs_quota_us
[0.008s][trace][os,container] CPU Quota is: -1
[0.008s][trace][os,container] Path to /cpu.cfs_period_us is /sys/fs/cgroup/cpu/cpu.cfs_period_us
[0.008s][trace][os,container] CPU Period is: 100000
[0.008s][trace][os,container] Path to /cpu.shares is /sys/fs/cgroup/cpu/cpu.shares
[0.008s][trace][os,container] CPU Shares is: 1024
[0.009s][trace][os,container] OSContainer::active_processor_count: 4
[0.009s][info ][pagesize    ] CodeHeap 'non-nmethods':  min=2496K max=5696K base=0x00007fa24090d000 page_size=4K size=5696K
[0.009s][info ][pagesize    ] CodeHeap 'profiled nmethods':  min=2496K max=120032K base=0x00007fa240e9d000 page_size=4K size=120032K
[0.009s][info ][pagesize    ] CodeHeap 'non-profiled nmethods':  min=2496K max=120032K base=0x00007fa2483d5000 page_size=4K size=120032K
[0.010s][info ][os,cpu      ] CPU:total 4 (initial active 4) (1 cores per cpu, 1 threads per core) family 6 model 142 stepping 10, cmov, cx8, fxsr, mmx, sse, sse2, sse3, ssse3, sse4.1, sse4.2, popcnt, avx, avx2, aes, clmul, erms, 3dnowpref, lzcnt, tsc, tscinvbit, bmi1, bmi2, fma
[0.010s][info ][os,cpu      ] CPU Model and flags from /proc/cpuinfo:
[0.010s][info ][os,cpu      ] model name  : Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz
[0.010s][info ][os,cpu      ] flags               : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht pbe syscall nx pdpe1gb lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq dtes64 ds_cpl ssse3 sdbg fma cx16 xtpr pcid sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch pti fsgsbase bmi1 avx2 bmi2 erms xsaveopt arat
[0.010s][info ][os,thread   ] Thread started (pthread id: 140335306258176, attributes: stacksize: 1024k, guardsize: 4k, detached).
[0.010s][info ][os,thread   ] Thread is alive (tid: 9, pthread id: 140335306258176).
[0.011s][info ][pagesize    ] Heap:  min=8M max=768M base=0x00000000d0000000 page_size=4K size=768M
[0.011s][info ][pagesize    ] Block Offset Table: req_size=1536K base=0x00007fa240389000 page_size=4K alignment=4K size=1536K
[0.011s][info ][pagesize    ] Card Table: req_size=1536K base=0x00007fa240209000 page_size=4K alignment=4K size=1536K
[0.011s][info ][pagesize    ] Card Counts Table: req_size=1536K base=0x00007fa240089000 page_size=4K alignment=4K size=1536K
[0.011s][info ][pagesize    ] Prev Bitmap: req_size=12M base=0x00007fa23b400000 page_size=4K alignment=4K size=12M
[0.011s][info ][pagesize    ] Next Bitmap: req_size=12M base=0x00007fa23a800000 page_size=4K alignment=4K size=12M
[0.011s][info ][os,thread   ] Thread started (pthread id: 140334742894336, attributes: stacksize: 1024k, guardsize: 4k, detached).
[0.011s][info ][os,thread   ] Thread is alive (tid: 10, pthread id: 140334742894336).
[0.011s][info ][os,thread   ] Thread started (pthread id: 140334741837568, attributes: stacksize: 1024k, guardsize: 4k, detached).
[0.011s][info ][os,thread   ] Thread is alive (tid: 11, pthread id: 140334741837568).
[0.012s][info ][os,thread   ] Thread started (pthread id: 140334703015680, attributes: stacksize: 1024k, guardsize: 4k, detached).
[0.012s][info ][os,thread   ] Thread is alive (tid: 12, pthread id: 140334703015680).
[0.012s][info ][os,thread   ] Thread started (pthread id: 140334499624704, attributes: stacksize: 1024k, guardsize: 4k, detached).
[0.012s][info ][os,thread   ] Thread is alive (tid: 13, pthread id: 140334499624704).
[0.021s][info ][os,thread   ] Thread started (pthread id: 140334490179328, attributes: stacksize: 1024k, guardsize: 4k, detached).
[0.021s][info ][os,thread   ] Thread is alive (tid: 14, pthread id: 140334490179328).
[0.024s][trace][os,container] Path to /cpu.cfs_quota_us is /sys/fs/cgroup/cpu/cpu.cfs_quota_us
[0.024s][trace][os,container] CPU Quota is: -1
[0.024s][trace][os,container] Path to /cpu.cfs_period_us is /sys/fs/cgroup/cpu/cpu.cfs_period_us
[0.024s][trace][os,container] CPU Period is: 100000
[0.024s][trace][os,container] Path to /cpu.shares is /sys/fs/cgroup/cpu/cpu.shares
[0.024s][trace][os,container] CPU Shares is: 1024
[0.024s][trace][os,container] OSContainer::active_processor_count: 4
[0.025s][info ][os,thread   ] Thread started (pthread id: 140334489122560, attributes: stacksize: 1024k, guardsize: 0k, detached).
[0.025s][info ][os,thread   ] Thread is alive (tid: 15, pthread id: 140334489122560).
[0.025s][info ][os,thread   ] Thread started (pthread id: 140334488069888, attributes: stacksize: 1024k, guardsize: 0k, detached).
[0.025s][info ][os,thread   ] Thread is alive (tid: 16, pthread id: 140334488069888).
[0.033s][info ][os,thread   ] Thread started (pthread id: 140334485497600, attributes: stacksize: 1024k, guardsize: 0k, detached).
[0.033s][info ][os,thread   ] Thread is alive (tid: 17, pthread id: 140334485497600).
[0.033s][info ][os,thread   ] Thread started (pthread id: 140334484444928, attributes: stacksize: 1024k, guardsize: 0k, detached).
[0.033s][info ][os,thread   ] Thread is alive (tid: 18, pthread id: 140334484444928).
[0.033s][info ][os,thread   ] Thread started (pthread id: 140334483392256, attributes: stacksize: 1024k, guardsize: 0k, detached).
[0.034s][info ][os,thread   ] Thread is alive (tid: 19, pthread id: 140334483392256).
[0.034s][info ][os,thread   ] Thread started (pthread id: 140334482339584, attributes: stacksize: 1024k, guardsize: 0k, detached).
[0.035s][info ][os,thread   ] Thread is alive (tid: 20, pthread id: 140334482339584).
[0.036s][trace][os,container] Path to /memory.limit_in_bytes is /sys/fs/cgroup/memory/memory.limit_in_bytes
[0.036s][trace][os,container] Memory Limit is: 5368709120
[0.036s][trace][os,container] Path to /memory.usage_in_bytes is /sys/fs/cgroup/memory/memory.usage_in_bytes
[0.036s][trace][os,container] Memory Usage is: 9551872
[0.037s][trace][os,container] Path to /memory.usage_in_bytes is /sys/fs/cgroup/memory/memory.usage_in_bytes
[0.037s][trace][os,container] Memory Usage is: 9682944
...
[0.058s][trace][os,container] Path to /memory.limit_in_bytes is /sys/fs/cgroup/memory/memory.limit_in_bytes
[0.058s][trace][os,container] Memory Limit is: 5368709120
[0.058s][trace][os,container] Path to /memory.usage_in_bytes is /sys/fs/cgroup/memory/memory.usage_in_bytes
[0.058s][trace][os,container] Memory Usage is: 12820480
...
[0.064s][info ][os,thread   ] Thread started (pthread id: 140334481286912, attributes: stacksize: 1024k, guardsize: 0k, detached).
[0.064s][info ][os,thread   ] Thread is alive (tid: 21, pthread id: 140334481286912).
...
[8005.132s][trace][os,container] Path to /memory.limit_in_bytes is /sys/fs/cgroup/memory/memory.limit_in_bytes
[8005.132s][trace][os,container] Memory Limit is: 5368709120
[8005.132s][trace][os,container] Path to /memory.usage_in_bytes is /sys/fs/cgroup/memory/memory.usage_in_bytes
[8005.132s][trace][os,container] Memory Usage is: 4093734912
[8014.238s][trace][os,container] Path to /memory.limit_in_bytes is /sys/fs/cgroup/memory/memory.limit_in_bytes
[8014.238s][trace][os,container] Memory Limit is: 5368709120
[8014.238s][trace][os,container] Path to /memory.usage_in_bytes is /sys/fs/cgroup/memory/memory.usage_in_bytes
[8014.238s][trace][os,container] Memory Usage is: 4093943808
...
----


==== GC logs

https://openjdk.java.net/jeps/271[JEP 271: Unified GC Logging]

[source]
----
-XX:+PrintGCDetails                                                        \
-XX:+PrintGCApplicationStoppedTime                                         \
-XX:+PrintGCApplicationConcurrentTime                                      \
-XX:+PrintGCCause                                                          \
-XX:+PrintTenuringDistribution                                             \
-XX:+PrintGCDateStamps                                                     \
-XX:+UseGCLogFileRotation                                                  \
-XX:NumberOfGCLogFiles=5                                                   \
-XX:GCLogFileSize=10M                                                      \
-Xloggc:/gclogs/`hostname`-`date +%FT%H-%M-%S`-gc.log                      \
----


[source]
----
-Xlog:
  gc*,       <1>
  gc+heap=debug,  <2>
  gc+ref=debug,  <3>
  gc+ergo*=trace, <4>
  gc+age*=trace, <5>
  gc+phases*, <6>
  safepoint*, <7>
  :file=/gclogs/%t-gc.log:time,uptime,tags:filecount=5,filesize=10M
----
<1> `PrintGCDetails`
<2> `PrintHeapAtGC`
<3> `PrintReferenceGC`
<4> `PrintAdaptiveSizePolicy`
<5> `PrintTenuringDistribution`
<6> `PrintParallelOldGCPhaseTimes`
<7> `PrintGCApplicationConcurrentTime` and `PrintGCApplicationStoppedTime`



.translation
[cols="m,a,a",options="headers"]
|===
| Old GC log flags usually set with `-XX:+...` | Equivalent tags with log level             | Definition of the the old flag

| PrintGC -Xloggc:<gc-log-file-path>           | `gc`                                       | Print message at garbage collection
| PrintGCDetails -Xloggc:<gc-log-file-path>    | `gc*`                                      | Print more details at garbage collection
| -verbose:gc                                  | `gc=trace` `gc+heap=trace` `gc+heap+exit=trace` `gc+metaspace=trace` `gc+sweep=debug` `gc+heap+ergo=debug` | Verbose GC

| PrintGCCause                                 | GC cause is now always logged              | Include GC cause in GC logging
| PrintGCID                                    | GC ID is now always logged                 | Print an identifier for each garbage collection

| PrintGCApplicationStoppedTime                | `safepoint`                                | Print the time the application has been stopped
| PrintGCApplicationConcurrentTime             | `safepoint`                                | Print the time the application has been running
| PrintTenuringDistribution                    | `gc+age*=trace`                            | Print tenuring age information

| PrintAdaptiveSizePolicy                      | `gc+ergo*=trace`                           | Print information about AdaptiveSizePolicy

| PrintHeapAtGC                                | `gc+heap=debug`                            | Print heap layout before and after each GC
| PrintHeapAtGCExtended                        | `gc+heap=trace`                            | Print extended information about the layout of the heap when -XX:+PrintHeapAtGC is set


| PrintClassHistogramBeforeFullGC              | `classhisto*=trace`                        | Print a class histogram before any major stop-world GC
| PrintClassHistogramAfterFullGC               | `classhisto*=trace`                        | Print a class histogram after any major stop-world GC

| PrintStringDeduplicationStatistics           | `gc+stringdedup*=debug`                    | Print string deduplication statistics

| PrintJNIGCStalls                             | `gc+jni=debug`                             | Print diagnostic message when GC is stalled by JNI critical section

| PrintReferenceGC                             | `gc+ref=debug`                             | Print times spent handling reference objects during GC

| PrintGCTaskTimeStamps                        | `task*=debug`                              | Print timestamps for individual gc worker thread tasks
| PrintTaskQueue                               | `gc+task+stats=trace`                      | Print taskqueue statistics for parallel collectors

| PrintPLAB                                    | `gc+plab=trace`                            | Print (survivor space) promotion LAB's sizing decisions
| PrintOldPLAB                                 | `gc+plab=trace`                            | Print (old gen) promotion LAB's sizing decisions
| PrintPromotionFailure                        | `gc+promotion=debug`                       | Print additional diagnostic information following promotion failure
| PrintTLAB                                    | `gc+tlab=trace`                            | Print various TLAB related information (augmented with `-XX:+TLABStats`)
| PrintTerminationStats                        | `gc+task+stats=debug`                      | Print termination statistics for parallel collectors

// G1GC
| G1PrintHeapRegions                           | `gc+region=trace`                          | If set G1 will print information on which regions are being allocated and which are reclaimed
| G1PrintRegionsLivenessInfo                   | `gc+liveness=trace`                        | Prints the liveness information for all regions in the heap at the end of a marking cycle
| G1SummarizeConcMark                          | `gc+marking=trace`                         | Summarize concurrent mark info
| G1SummarizeRSets                             | `gc+remset*=trace`                         | Summarize remembered set processing info
| G1TraceConcRefinement                        | `gc+refine=debug`                          | Trace G1 concurrent refinement
| G1TraceEagerReclaimHumongousObjects          | `gc+humongous=debug`                       | Print some information about large object liveness at every young GC
| G1TraceStringSymbolTableScrubbing            | `gc+stringdedup=trace`                     | Trace information string and symbol table scrubbing

// ParallelOldGC
| PrintParallelOldGCPhaseTimes                 | `gc+phases=trace`                          | Print the time taken by each phase in ParallelOldGC


// CMS
| CMSDumpAtPromotionFailure                    | `gc+promotion=trace`                       | Dump useful information about the state of the CMS old generation upon a promotion failure (complemented by flags `CMSPrintChunksInDump` or `CMSPrintObjectsInDump`)
| CMSPrintEdenSurvivorChunks                   | `gc+heap=trace`                            | Print the eden and the survivor chunks used for the parallel initial mark or remark of the eden/survivor spaces
| PrintCMSInitiationStatistics                 | `gc=trace`                                 | Statistics for initiating a CMS collection
| PrintCMSStatistics                           | `gc=debug` (`trace`) `gc+task=trace` `gc+survivor=trace` `log+sweep=debug` (`trace`) | Statistics for CMS (complemented by `CMSVerifyReturnedBytes`)
| PrintFLSCensus                               | `gc+freelist+census=debug`                 | Census for CMS' FreeListSpace
| PrintFLSStatistics                           | `gc+freelist+stats=debug` (`trace`) `gc+freelist*=debug` (`trace`) | Statistics for CMS' FreeListSpace
| TraceCMSState                                | `gc+state=debug`                           | Trace the state of the CMS collection



| TraceAdaptativeGCBoundary                    | `heap+ergo=debug`                          | Trace young-old boundary moves
| TraceDynamicGCThreads                        | `gc+task=trace`                            | Trace the dynamic GC thread usage
| TraceMetadataHumongousAllocation             | `gc+metaspace+alloc=debug`                 | Trace humongous metadata allocations

| VerifySilently                               | `gc+verify=debug`                          | Do not print the verification progress


|===


.decorators
[cols="m,m"]
|===

| PrintGCDateStamps                            | time
| PrintGCTimeStamps                            | uptime

|===

.log on demand, with G1 region tracing
[source,bash]
----
jcmd $(pidof java) \
  VM.log \
    what="gc*=debug,gc+ergo*=trace,gc+age*=trace,gc+region=trace,gc+liveness=trace,safepoint*,os*" \
    decorators=uptime,time,tags,level \
    output="file=/gclogs/%t-gc-trace.log" \
    output_options="filecount=10,filesize=20M"
----

From https://twitter.com/poonam_bajaj[Poonam Bajaj Parhar],s talk on
https://www.slideshare.net/PoonamBajaj5/lets-learn-to-talk-to-gc-logs-in-java-9[unified GC logs]

https://bugs.java.com/bugdatabase/view_bug.do?bug_id=JDK-8145092
https://hg.openjdk.java.net/jdk9/jdk9/hotspot/rev/f944761a3ce3
log prefixes : https://hg.openjdk.java.net/jdk9/jdk9/hotspot/rev/f944761a3ce3#l120.8

https://docs.oracle.com/javase/9/tools/java.htm#JSWOR-GUID-BE93ABDC-999C-4CB5-A88B-1994AAAC74D5




==== Classes

[cols="m,a"]
|===

| TraceClassInitialization     | `class+init=info`
| TraceClassLoading            | `class+load=info` (`debug)`
| TraceClassLoadingPreorder    | `class+preorder=debug`
| TraceClassUnloading          | `class+unload=info` (`trace)`
| TraceClassPaths              | `class+path=info`
| TraceClassResolution         | `class+resolve=debug`
| TraceRedefineClasses         | `redefine+class*=info` (`debug`, `trace)`
| TraceLoaderConstraints       | `class+loader+constraints=info`
| TraceClassLoaderData         | `class+loader+data=debug` (`trace)`

| TraceSafepoint               | `safepoint=debug`
| TraceSafepointCleanupTime    | `safepoint+cleanup=info`

| TraceMonitorInflation        | `monitorinflation=debug`
| TraceBiasedLocking           | `biasedlocking=info` (`trace)`

| TraceExceptions              | `exceptions=info`

| VerboseVerification          | `verification=info`

|===


Source : https://github.com/corretto/corretto-11/blob/2b351313740f148597cf680d8443df93931de813/src/src/hotspot/share/runtime/arguments.cpp#L602-L636[src/hotspot/share/runtime/arguments.cpp]

[source, c++]
----
// NOTE: A compatibility request will be necessary for each alias to be removed.
static AliasedLoggingFlag const aliased_logging_flags[] = {
  { "PrintCompressedOopsMode",   LogLevel::Info,  true,  LOG_TAGS(gc, heap, coops) },
  { "PrintSharedSpaces",         LogLevel::Info,  true,  LOG_TAGS(cds) },
  { "TraceBiasedLocking",        LogLevel::Info,  true,  LOG_TAGS(biasedlocking) },
  { "TraceClassLoading",         LogLevel::Info,  true,  LOG_TAGS(class, load) },
  { "TraceClassLoadingPreorder", LogLevel::Debug, true,  LOG_TAGS(class, preorder) },
  { "TraceClassPaths",           LogLevel::Info,  true,  LOG_TAGS(class, path) },
  { "TraceClassResolution",      LogLevel::Debug, true,  LOG_TAGS(class, resolve) },
  { "TraceClassUnloading",       LogLevel::Info,  true,  LOG_TAGS(class, unload) },
  { "TraceExceptions",           LogLevel::Info,  true,  LOG_TAGS(exceptions) },
  { "TraceLoaderConstraints",    LogLevel::Info,  true,  LOG_TAGS(class, loader, constraints) },
  { "TraceMonitorInflation",     LogLevel::Debug, true,  LOG_TAGS(monitorinflation) },
  { "TraceSafepointCleanupTime", LogLevel::Info,  true,  LOG_TAGS(safepoint, cleanup) },
  { "TraceJVMTIObjectTagging",   LogLevel::Debug, true,  LOG_TAGS(jvmti, objecttagging) },
  { "TraceRedefineClasses",      LogLevel::Info,  false, LOG_TAGS(redefine, class) },
  { NULL,                        LogLevel::Off,   false, LOG_TAGS(_NO_TAG) }
};

#ifndef PRODUCT
// These options are removed in jdk9. Remove this code for jdk10.
static AliasedFlag const removed_develop_logging_flags[] = {
  { "TraceClassInitialization",   "-Xlog:class+init" },
  { "TraceClassLoaderData",       "-Xlog:class+loader+data" },
  { "TraceDefaultMethods",        "-Xlog:defaultmethods=debug" },
  { "TraceItables",               "-Xlog:itables=debug" },
  { "TraceMonitorMismatch",       "-Xlog:monitormismatch=info" },
  { "TraceSafepoint",             "-Xlog:safepoint=debug" },
  { "TraceStartupTime",           "-Xlog:startuptime" },
  { "TraceVMOperation",           "-Xlog:vmoperation=debug" },
  { "PrintVtables",               "-Xlog:vtables=debug" },
  { "VerboseVerification",        "-Xlog:verification" },
  { NULL, NULL }
};
#endif //PRODUCT
----


==== tags

[cols="a,m"]
|===

| Region                                         | region
| Liveness                                       | liveness
| Marking                                        | marking
| Remembered Set                                 | remset
| Ergonomics                                     | ergo
| Class Histogram                                | classhisto
| Safepoint                                      | safepoint
| Task                                           | task
| Heap                                           | heap
| JNI                                            | jni
| Promotion(Parallel) Local Allocation Buffer    | plab
| Promotion                                      | promotion
| Reference                                      | ref
| String Deduplication                           | stringdedup
| Statistics                                     | stats
| Tenuring                                       | age
| Thread Local Allocation Buffer                 | tlab
| Metaspace                                      | metaspace
| Humongous Allocation                           | alloc
| Refinement                                     | refine
| Humongous                                      | humongous
| String Symbol Table                            | stringtable

|===


gc,age
gc,alloc,region
gc,cpu
gc,ergo
gc,ergo,cset
gc,ergo,ihop
gc,ergo,refine
gc,heap
gc,humongous
gc,ihop
gc,jni
gc,marking
gc,metaspace
gc,mmu
gc,phases
gc,phases,ref
gc,phases,start
gc,plab
gc,ref
gc,ref,start
gc,refine
gc,remset,tracking
gc,start
gc,stats
gc,stringdedup
gc,stringtable
gc,task
gc,task,stats
gc,tlab