---
authors: ["brice.dutheil"]
date: "2020-04-24T11:54:58+02:00"
language: en
draft: true
#tags: ["log","jvm","java","unified logging", "jep-158", "jep-271"]
slug: "exploring-jvm-unified-logs-jep-158-jep-271"
title: "Exploring JVM unified logs (JEP-158 / JEP-271)"
---

For people that were used to pre-jdk8 options, we knew our via explicit options
in particular for GC logging, but occasionally to other options like those that trace
class loading and unloading, or even more _obscure_ options.

From JDK 9, the JVM maintainers chose to overhaul the way JVM logs things.
JDK 9 may seem old news today but I still find it difficult to know what to log.
Very well written blogs such as https://blog.codefx.org/java/unified-logging-with-the-xlog-option/[this one]
from https://twitter.com/nipafx[Nicolai Parlog] usually only touch the surface of unified logging and usually
focus on GC logs.
The official documentation only refer to old options and their unified logging counter part.
The issue I think unified logging has is do not account for the abundance of possibilities
and especially how it can help you gain insight on the VM components.

On the GC side for example some information like the IHOP can only be found
if the proper logging tag at the right level are set. In my opinion the flexibility
of this logging system make it's configuration even more obscure compared to
the previous logging explicit and searchable JVM option.

Anyway, let's begin ou exploration with a small recapitulation of https://openjdk.java.net/jeps/158[JEP-158]
which lays out the foundation of JVM unified logging.

== Unified JVM Logging (JEP-158)

The JEP describes how the logging configuration works in the command line :

.java log configuration command line syntax
[%collapsible]
====

[source]
----
-Xlog[:option]
    option         :=  [<what>][:[<output>][:[<decorators>][:<output-options>]]]
                       'help'
                       'disable'
    what           :=  <selector>[,...]
    selector       :=  <tag-set>[*][=<level>]
    tag-set        :=  <tag>[+...]
                       'all'
    tag            :=  name of tag
    level          :=  trace
                       debug
                       info
                       warning
                       error
    output         :=  'stderr'
                       'stdout'
                       [file=]<filename>
    decorators     :=  <decorator>[,...]
                       'none'
    decorator      :=  time
                       uptime
                       timemillis
                       uptimemillis
                       timenanos
                       uptimenanos
                       pid
                       tid
                       level
                       tags
    output-options :=  <output_option>[,...]
    output-option  :=  filecount=<file count>
                       filesize=<file size>
                       parameter=value
----

====

Note that it's possible to have multiple log configuration simply by adding new `-Xlog...` options.
However, the output must be unique in these logs, otherwise the last one will override the previous log
configuration.

Also, if you already heard of `jcmd`, unified logging JEP made the log configurable at runtime.
_If you didn't hear about `jcmd` you really should check it out it's the future
of the serviceability / diagnostic command on the JDK._

.A note about `jcmd`
____
*Controlling at runtime*

Logging can be controlled at runtime through Diagnostic Commands (the `jcmd` utility).
Everything that can be specified on the command line can also be specified dynamically
with Diagnostic Commands. Since diagnostic commands are automatically exposed as MBeans
it will be possible to use JMX to change logging configuration in runtime.
____


Now let's explore unified logging

== Useful usage of unified logging

=== How to use the tool, help from the command line

While the JEP explains things, it's usually not how we get the first contact, we use the
command line help, which is describing just as well how to use on the command line.

Also, you may have to enable logs on a running VM, well in this case the `jcmd` sub-command `VM.log`
is your tool.

.`java` command
[source,shell,role="primary"]
----
$ java -Xlog:help
-Xlog Usage: -Xlog[:[selections][:[output][:[decorators][:output-options]]]]
         where 'selections' are combinations of tags and levels of the form tag1[+tag2...][*][=level][,...]
         NOTE: Unless wildcard (*) is specified, only log messages tagged with exactly the tags specified will be matched.

Available log levels:
 off, trace, debug, info, warning, error

Available log decorators:
 time (t), utctime (utc), uptime (u), timemillis (tm), uptimemillis (um), timenanos (tn), uptimenanos (un), hostname (hn), pid (p), tid (ti), level (l), tags (tg)
 Decorators can also be specified as 'none' for no decoration.

Available log tags:
 add, age, alloc, annotation, aot, arguments, attach, barrier, biasedlocking, blocks, bot, breakpoint, bytecode, cds, census, class, classhisto, cleanup, codecache, compaction, compilation, constantpool, constraints, container, coops, cpu, cset, data, datacreation, dcmd, decoder, defaultmethods, director, dump, ergo, event, exceptions, exit, fingerprint, free, freelist, gc, handshake, hashtables, heap, humongous, ihop, iklass, init, inlining, interpreter, itables, jfr, jit, jni, jvmti, liveness, load, loader, logging, malloc, mark, marking, membername, memops, metadata, metaspace, methodcomparator, mirror, mmu, module, monitorinflation, monitormismatch, nestmates, nmethod, normalize, objecttagging, obsolete, oldobject, oom, oopmap, oops, oopstorage, os, pagesize, parser, patch, path, perf, phases, plab, preorder, preview, promotion, protectiondomain, purge, redefine, ref, refine, region, reloc, remset, resolve, safepoint, sampling, scavenge, setting, smr, stackmap, stacktrace, stackwalk, start, startuptime, state, stats, stringdedup, stringtable, subclass, survivor, sweep, system, table, task, thread, time, timer, tlab, tracking, unload, unshareable, update, verification, verify, vmoperation, vmthread, vtables, vtablestubs, workgang
 Specifying 'all' instead of a tag combination matches all tag combinations.

Described tag sets:
 logging: Logging for the log framework itself

Available log outputs:
 stdout/stderr
 file=<filename>
  If the filename contains %p and/or %t, they will expand to the JVM's PID and startup timestamp, respectively.
  Additional output-options for file outputs:
   filesize=..  - Target byte size for log rotation (supports K/M/G suffix). If set to 0, log rotation will not trigger automatically, but can be performed manually (see the VM.log DCMD).
   filecount=.. - Number of files to keep in rotation (not counting the active file). If set to 0, log rotation is disabled. This will cause existing log files to be overwritten.

Some examples:
 -Xlog
         Log all messages up to 'info' level to stdout with 'uptime', 'levels' and 'tags' decorations.
         (Equivalent to -Xlog:all=info:stdout:uptime,levels,tags).

 -Xlog:gc
         Log messages tagged with 'gc' tag up to 'info' level to stdout, with default decorations.

 -Xlog:gc,safepoint
         Log messages tagged either with 'gc' or 'safepoint' tags, both up to 'info' level, to stdout, with default decorations.
         (Messages tagged with both 'gc' and 'safepoint' will not be logged.)

 -Xlog:gc+ref=debug
         Log messages tagged with both 'gc' and 'ref' tags, up to 'debug' level, to stdout, with default decorations.
         (Messages tagged only with one of the two tags will not be logged.)

 -Xlog:gc=debug:file=gc.txt:none
         Log messages tagged with 'gc' tag up to 'debug' level to file 'gc.txt' with no decorations.

 -Xlog:gc=trace:file=gctrace.txt:uptimemillis,pid:filecount=5,filesize=1m
         Log messages tagged with 'gc' tag up to 'trace' level to a rotating fileset of 5 files of size 1MB,
         using the base name 'gctrace.txt', with 'uptimemillis' and 'pid' decorations.

 -Xlog:gc::uptime,tid
         Log messages tagged with 'gc' tag up to 'info' level to output 'stdout', using 'uptime' and 'tid' decorations.

 -Xlog:gc*=info,safepoint*=off
         Log messages tagged with at least 'gc' up to 'info' level, but turn off logging of messages tagged with 'safepoint'.
         (Messages tagged with both 'gc' and 'safepoint' will not be logged.)

 -Xlog:disable -Xlog:safepoint=trace:safepointtrace.txt
         Turn off all logging, including warnings and errors,
         and then enable messages tagged with 'safepoint' up to 'trace' level to file 'safepointtrace.txt'.
----

.`jcmd` command
[source,role="secondary"]
----
$ jcmd $(pidof java) help VM.log
6:
VM.log
Lists current log configuration, enables/disables/configures a log output, or rotates all logs.

Impact: Low: No impact

Permission: java.lang.management.ManagementPermission(control)

Syntax : VM.log [options]

Options: (options must be specified using the <key> or <key>=<value> syntax)
        output : [optional] The name or index (#<index>) of output to configure. (STRING, no default value)
        output_options : [optional] Options for the output. (STRING, no default value)
        what : [optional] Configures what tags to log. (STRING, no default value)
        decorators : [optional] Configures which decorators to use. Use 'none' or an empty value to remove all. (STRING, no default value)
        disable : [optional] Turns off all logging and clears the log configuration. (BOOLEAN, no default value)
        list : [optional] Lists current log configuration. (BOOLEAN, no default value)
        rotate : [optional] Rotates all logs. (BOOLEAN, no default value)
----


==== configuring unified logging

From the help and the JEP above here's what to retain :

Tags::
When a log message is shown, it should be associated with a set of tags in the JVM which identify by names: `os`, `gc`, `modules`…

– We can apply different settings for individual tags.
– `\*` denotes _wildcard_ tag match. Not using `*` means all messages matching exactly the specified tags.

Levels::
We can perform logging at different levels. The available levels are `error`, `warning`, `info`, `debug`, `trace` and `develop`.

To disable logging, use the alternative `off`.

Outputs::
The output currently supports 3 types: stdout, stderr, or a text file, which can be set up for log file rotation based on written size and a number of files to rotate (for example: each 10MB, keep 5 files in rotation)

Decorators::
There are more details about the message called decorators. Here is the list:

* `time`/`timemillis`/`timenanos`: current time and date (ISO-8601 format)
* `uptime`/`uptimemillis`/`uptimenanos`: time since the start of the JVM
* `pid`: process identifier
* `tid`: thread identifier
* `level`: level associated with the log message
* `tags`: tag associated with the log message

Default settings::
.. tag-set: `all`.
.. level: `info`
.. output: `stdout`
.. decorators: `uptime`, `level`, `tags`

In practice this will give :

.`java` command
[source,role="primary"]
----
-Xlog:pagesize,os*,os+container=trace:file=/var/log/%t-os-container-pagezise.log:uptime,tags,level
----

.`jcmd` command
[source,role"secondary"]
----
$ jcmd $(pidof java) VM.log output=/var/log/%t-os-container-pagezise.log what=pagesize,os*,os+container=trace decorators=uptime,tags,level
----

The above commands are equivalent, but note that depending on the specified tags and level, the log content
may be less useful when enabled at a later time. In the above example in particular the `os+container=trace`
will output some interesting logs only during JVM startup.

==== Tag prefixes / Tag set TODO

https://github.com/AdoptOpenJDK/openjdk-jdk11u/commit/fc2a1798bac1bfda6929dc55936ba7f9e4cf0208#diff-c7fbf2952ef86b686c1849f6735041c9R30-R35



=== Migrating the GC log configuration (JEP-271)

While this topic may seem covered by other blogs I wasn't satisfied by the actual
equivalence or not of the log configuration. I got the configuration wrong _as in incomplete_
several times until I decided to dive in.

GC unified logging is covered by another JEP, https://openjdk.java.net/jeps/271[JEP 271: Unified GC Logging],
which rely on JEP-158 as mentioned earlier. However, this JEP is much more concise and
barely elaborate how the previous logging option will be turned in unified logs.

One of the best source came from https://twitter.com/poonam_bajaj[Poonam Bajaj Parhar],s talk on
https://www.slideshare.net/PoonamBajaj5/lets-learn-to-talk-to-gc-logs-in-java-9[unified GC logs]
However the most interesting data is not searchable because it's an image of a table and
everything is not there, for the poor souls that need to work with other GCs.

The basic translation of the following usual GC logging configuration :

.pre-jdk9
[source]
----
-XX:+PrintGCDetails                           \
-XX:+PrintGCApplicationStoppedTime            \
-XX:+PrintGCApplicationConcurrentTime         \
-XX:+PrintGCCause                             \
-XX:+PrintGCID                                \
-XX:+PrintTenuringDistribution                \
-XX:+PrintGCDateStamps                        \
-XX:+UseGCLogFileRotation                     \
-XX:NumberOfGCLogFiles=5                      \
-XX:GCLogFileSize=10M                         \
-Xloggc:/var/log/`date +%FT%H-%M-%S`-gc.log   \
----

These flags could be translated to the following configuration :

.log config
[source,role="primary"]
----
-Xlog:gc*,gc+heap=debug,gc+ref=debug,gc+ergo*=trace,gc+age*=trace,gc+phases*=debug,safepoint*:file=/var/log/%t-gc.log:uptime,tags,level:filecount=10,filesize=20M
----

.log config breakdown
[source,role="secondary"]
----
-Xlog:
  gc*, <1>
  gc+heap=debug, <2>
  gc+ref=debug, <3>
  gc+ergo*=trace, <4>
  gc+age*=trace, <5>
  gc+phases*=debug, <6>
  safepoint* <7>
  :file=/var/log/%t-gc.log <8>
  :time,tags,level <9>
  :filecount=5,filesize=10M <10>
----
<1> `PrintGCDetails` (remember that default level is `info`)
<2> `PrintHeapAtGC`
<3> `PrintReferenceGC`
<4> `PrintAdaptiveSizePolicy`
<5> `PrintTenuringDistribution`
<6> `PrintParallelOldGCPhaseTimes`
<7> `PrintGCApplicationConcurrentTime` and `PrintGCApplicationStoppedTime`
<8> `Xloggc`
<9> `PrintGCDateStamps` (but also decorates with tags and level, useful to know identify the source of the log).
<10> `UseGCLogFileRotation`, `NumberOfGCLogFiles`, `GCLogFileSize`

Note that some options do not have equivalents in unified GC logging.
Either because the tag system is more precise, or because the log message
themselves changed, e.g. the GC cause and the GC id are now always logged.

Now it's the right opportunity to warn about the slight caveats of this log configuration.

This configuration is fine and work reasonably well, BUT this configuration
actually may misses some log like some `ihop`, which is not only logged with the `ergo` tag
as we'll see.

==== Exhaustive translation table

I extracted the following table from the actual patches that implemented JEP-271, see
https://bugs.openjdk.java.net/browse/JDK-8059805[JDK-8059805],
https://bugs.openjdk.java.net/browse/JDK-8145092[JDK-8145092], and in particular the
https://hg.openjdk.java.net/jdk9/jdk9/hotspot/rev/f944761a3ce3[related diff] https://github.com/AdoptOpenJDK/openjdk-jdk11u/commit/d724e8a3489f8ebb57c7bbf82784a2b2d537fdc8[(on github)].

In a lesser way I sued the official https://docs.oracle.com/javase/9/tools/java.htm#JSWOR-GUID-BE93ABDC-999C-4CB5-A88B-1994AAAC74D5[`java` documentation],
which I found somewhat lacking in this regard.


.Exhaustive GC logging option translation table (with some caveats)
[cols="m,a,a",options="headers"]
|===
| Old GC log flags usually set with `-XX:+...` | `Equivalent` tags with log level           | Definition of the the old flag

| PrintGC -Xloggc:<gc-log-file-path>           | `gc`                                       | Print message at garbage collection
| PrintGCDetails -Xloggc:<gc-log-file-path>    | `gc*`                                      | Print more details at garbage collection
| -verbose:gc                                  | `gc=trace` `gc+heap=trace` `gc+heap+exit=trace` `gc+metaspace=trace` `gc+sweep=debug` `gc+heap+ergo=debug` | Verbose GC

| PrintGCCause                                 | `GC` cause is now always logged            | Include GC cause in GC logging
| PrintGCID                                    | `GC` ID is now always logged               | Print an identifier for each garbage collection

| PrintGCApplicationStoppedTime                | `safepoint`                                | Print the time the application has been stopped
| PrintGCApplicationConcurrentTime             | `safepoint`                                | Print the time the application has been running
| PrintTenuringDistribution                    | `gc+age*=trace`                            | Print tenuring age information

| PrintAdaptiveSizePolicy                      | `gc+ergo*=trace`                           | Print information about AdaptiveSizePolicy

| PrintHeapAtGC                                | `gc+heap=debug`                            | Print heap layout before and after each GC
| PrintHeapAtGCExtended                        | `gc+heap=trace`                            | Print extended information about the layout of the heap when -XX:+PrintHeapAtGC is set


| PrintClassHistogramBeforeFullGC              | `classhisto*=trace`                        | Print a class histogram before any major stop-world GC
| PrintClassHistogramAfterFullGC               | `classhisto*=trace`                        | Print a class histogram after any major stop-world GC

| PrintStringDeduplicationStatistics           | `gc+stringdedup*=debug`                    | Print string deduplication statistics

| PrintJNIGCStalls                             | `gc+jni=debug`                             | Print diagnostic message when GC is stalled by JNI critical section

| PrintReferenceGC                             | `gc+ref=debug`                             | Print times spent handling reference objects during GC

| PrintGCTaskTimeStamps                        | `task*=debug`                              | Print timestamps for individual gc worker thread tasks
| PrintTaskQueue                               | `gc+task+stats=trace`                      | Print taskqueue statistics for parallel collectors

| PrintPLAB                                    | `gc+plab=trace`                            | Print (survivor space) promotion LAB's sizing decisions
| PrintOldPLAB                                 | `gc+plab=trace`                            | Print (old gen) promotion LAB's sizing decisions
| PrintPromotionFailure                        | `gc+promotion=debug`                       | Print additional diagnostic information following promotion failure
| PrintTLAB                                    | `gc+tlab=trace`                            | Print various TLAB related information (augmented with `-XX:+TLABStats`)
| PrintTerminationStats                        | `gc+task+stats=debug`                      | Print termination statistics for parallel collectors

// G1GC
| G1PrintHeapRegions                           | `gc+region=trace`                          | If set G1 will print information on which regions are being allocated and which are reclaimed
| G1PrintRegionsLivenessInfo                   | `gc+liveness=trace`                        | Prints the liveness information for all regions in the heap at the end of a marking cycle
| G1SummarizeConcMark                          | `gc+marking=trace`                         | Summarize concurrent mark info
| G1SummarizeRSets                             | `gc+remset*=trace`                         | Summarize remembered set processing info
| G1TraceConcRefinement                        | `gc+refine=debug`                          | Trace G1 concurrent refinement
| G1TraceEagerReclaimHumongousObjects          | `gc+humongous=debug`                       | Print some information about large object liveness at every young GC
| G1TraceStringSymbolTableScrubbing            | `gc+stringdedup=trace`                     | Trace information string and symbol table scrubbing

// ParallelOldGC
| PrintParallelOldGCPhaseTimes                 | `gc+phases=trace`                          | Print the time taken by each phase in ParallelOldGC


// CMS
| CMSDumpAtPromotionFailure                    | `gc+promotion=trace`                       | Dump useful information about the state of the CMS old generation upon a promotion failure (complemented by flags `CMSPrintChunksInDump` or `CMSPrintObjectsInDump`)
| CMSPrintEdenSurvivorChunks                   | `gc+heap=trace`                            | Print the eden and the survivor chunks used for the parallel initial mark or remark of the eden/survivor spaces
| PrintCMSInitiationStatistics                 | `gc=trace`                                 | Statistics for initiating a CMS collection
| PrintCMSStatistics                           | `gc=debug` (`trace`) `gc+task=trace` `gc+survivor=trace` `log+sweep=debug` (`trace`) | Statistics for CMS (complemented by `CMSVerifyReturnedBytes`)
| PrintFLSCensus                               | `gc+freelist+census=debug`                 | Census for CMS' FreeListSpace
| PrintFLSStatistics                           | `gc+freelist+stats=debug` (`trace`) `gc+freelist*=debug` (`trace`) | Statistics for CMS' FreeListSpace
| TraceCMSState                                | `gc+state=debug`                           | Trace the state of the CMS collection

// safepoints
| TraceSafepoint                               | `safepoint=debug`                          | Trace application pauses due to VM operations in safepoints
| TraceSafepointCleanupTime                    | `safepoint+cleanup=info`                   | break down of clean up tasks performed during safepoint


| TraceAdaptativeGCBoundary                    | `heap+ergo=debug`                          | Trace young-old boundary moves
| TraceDynamicGCThreads                        | `gc+task=trace`                            | Trace the dynamic GC thread usage
| TraceMetadataHumongousAllocation             | `gc+metaspace+alloc=debug`                 | Trace humongous metadata allocations

| VerifySilently                               | `gc+verify=debug`                          | Do not print the verification progress


|===


.old option are now decorators
[cols="m,m"]
|===

| PrintGCDateStamps                            | time
| PrintGCTimeStamps                            | uptime

|===

==== Caveat when using this translation table

I noticed while analyzing GC logs with the above unified logging configuration that some logs
I expected were missing, and while doing this translation table I identified the logs I expected.
They had a different _tag_ prefixes.

On the example of heap occupancy logs (IHOP), it was logged with `PrintAdaptiveSizePolicy`
and now it's supposed to be logged as part of the GC ergonomics by setting `gc+ergo*` to `trace`.
Looking at the code, I noticed the `ihop` tag is not always prefixed by `gc` and `ergo`.

This tag is not alone, in the https://github.com/AdoptOpenJDK/openjdk-jdk11u/commit/d724e8a3489f8ebb57c7bbf82784a2b2d537fdc8[diff]
I mentioned there's an interesting file that describes GC log prefixes. The diff is huge and
may take some time to load, search for the following file
https://github.com/AdoptOpenJDK/openjdk-jdk11u/commit/d724e8a3489f8ebb57c7bbf82784a2b2d537fdc8#diff-c7fbf2952ef86b686c1849f6735041c9[src/share/vm/logging/logPrefix.hpp].

Also, JDK maintainers improve the JVM sub-systems logging over time, possibly backporting improvements.
This makes the tag selection hard to use properly and hard to maintain correctly. Very few will _grep_ the
JDK code base to track which tag they need to tune GCs which is already arcane enough.

In this sense I believe that if we configure/select tags too restrictively it might be counter-productive.

==== Embracing unified logging for GC logs

This led to think that instead of trying to _mimic_ old logging options, I should instead
prefer to log more tags and simplify the overall logging configuration.

.log config
[source, role="primary"]
----
-Xlog:gc*=debug,gc+ergo*=trace,gc+age*=trace,safepoint*:file=/gclogs/%t-gc.log:uptime,tags,level:filecount=10,filesize=20M
----

.log config breakdown
[source, role="secondary"]
----
-Xlog:
  gc*=debug, <1>
  gc+ergo*=trace, <2>
  gc+age*=trace, <3>
  safepoint*
  :file=/gclogs/%t-gc.log:uptime,tags,level:filecount=10,filesize=20M
----
<1> Logs everything under `gc` at `debug` level.
<2> Specific tagset level configuration for ergonomics.
<3> Specific tagset level configuration for tenuring distribution.

The above configuration is simple at the expanse of possibly larger file size.
Also, using `gc*=debug` allows to catch extra tags, and possibly new `gc` related tags
that show up. In my opinion this configuration does not have any caveats.

And as mentioned I benefited from other tags under `gc` that I wasn't even looking
at before because I simply didn't think to enable the logging option,
like `PrintJNIGCStalls` in pre-jdk9 `jni` tag in unified logging or dreaded humongous
allocations in G1GC via the `humongous` tag.
In short this simpler configuration enabled more logging, which means GC analysis tool
can spot other useful information.

.GC tagsets with `gc*=debug` configuration
* `gc,age`
* `gc,alloc,region`
* `gc,cpu`
* `gc,ergo`
* `gc,ergo,cset`
* `gc,ergo,ihop`
* `gc,ergo,refine`
* `gc,heap`
* `gc,humongous`
* `gc,ihop`
* `gc,jni`
* `gc,marking`
* `gc,metaspace`
* `gc,mmu`
* `gc,phases`
* `gc,phases,ref`
* `gc,phases,start`
* `gc,plab`
* `gc,ref`
* `gc,ref,start`
* `gc,refine`
* `gc,remset,tracking`
* `gc,start`
* `gc,stats`
* `gc,stringdedup`
* `gc,stringtable`
* `gc,task`
* `gc,task,stats`
* `gc,tlab`


==== Try GC logging configurations

Unlike `os` and `container` logs, GC happens almost continuously this opens the opportunity
to try log configurations at runtime using `jcmd`. In the example below I wanted to monitor
more thoroughly G1GC regions:

.Activate a new log configuration
[source,bash]
----
jcmd $(pidof java) \
  VM.log \
    what="gc*=debug,gc+ergo*=trace,gc+age*=trace,gc+region=trace,gc+liveness=trace,safepoint*" \
    decorators=time,tags,level \
    output="file=/var/log/%t-gc-region-tracing.log" \
    output_options="filecount=10,filesize=20M"
----

=== Migrating other options

One thing I used to log is about classes, particularly during development.
Especially loading and unloading. I sued this a lot while debugging some aspects of Mockito
and some application servers back in the days.

Some of the `Trace*` options are still present, even in JDK 14, although they output a warning.

.Other tracing option translation
[cols="m,a"]
|===

| TraceClassInitialization     | `class+init=info`
| TraceClassLoading            | `class+load=info` (`debug)`
| TraceClassLoadingPreorder    | `class+preorder=debug`
| TraceClassUnloading          | `class+unload=info` (`trace)`
| TraceClassPaths              | `class+path=info`
| TraceClassResolution         | `class+resolve=debug`
| TraceLoaderConstraints       | `class+loader+constraints=info`
| TraceClassLoaderData         | `class+loader+data=debug` (`trace)`

| TraceRedefineClasses         | `redefine+class*=info` (`debug`, `trace)`

| TraceMonitorInflation        | `monitorinflation=debug`
| TraceBiasedLocking           | `biasedlocking=info` (`trace)`

| TraceExceptions              | `exceptions=info`

| TraceJVMTIObjectTagging      | `jvmti+objecttagging=debug`


|===

.Tracing option declaration in the JVM code base
[%collapsible]
====
.https://github.com/corretto/corretto-11/blob/2b351313740f148597cf680d8443df93931de813/src/src/hotspot/share/runtime/arguments.cpp#L602-L636[src/hotspot/share/runtime/arguments.cpp]
[source, c++]
----
// NOTE: A compatibility request will be necessary for each alias to be removed.
static AliasedLoggingFlag const aliased_logging_flags[] = {
  { "PrintCompressedOopsMode",   LogLevel::Info,  true,  LOG_TAGS(gc, heap, coops) },
  { "PrintSharedSpaces",         LogLevel::Info,  true,  LOG_TAGS(cds) },
  { "TraceBiasedLocking",        LogLevel::Info,  true,  LOG_TAGS(biasedlocking) },
  { "TraceClassLoading",         LogLevel::Info,  true,  LOG_TAGS(class, load) },
  { "TraceClassLoadingPreorder", LogLevel::Debug, true,  LOG_TAGS(class, preorder) },
  { "TraceClassPaths",           LogLevel::Info,  true,  LOG_TAGS(class, path) },
  { "TraceClassResolution",      LogLevel::Debug, true,  LOG_TAGS(class, resolve) },
  { "TraceClassUnloading",       LogLevel::Info,  true,  LOG_TAGS(class, unload) },
  { "TraceExceptions",           LogLevel::Info,  true,  LOG_TAGS(exceptions) },
  { "TraceLoaderConstraints",    LogLevel::Info,  true,  LOG_TAGS(class, loader, constraints) },
  { "TraceMonitorInflation",     LogLevel::Debug, true,  LOG_TAGS(monitorinflation) },
  { "TraceSafepointCleanupTime", LogLevel::Info,  true,  LOG_TAGS(safepoint, cleanup) },
  { "TraceJVMTIObjectTagging",   LogLevel::Debug, true,  LOG_TAGS(jvmti, objecttagging) },
  { "TraceRedefineClasses",      LogLevel::Info,  false, LOG_TAGS(redefine, class) },
  { NULL,                        LogLevel::Off,   false, LOG_TAGS(_NO_TAG) }
};

#ifndef PRODUCT
// These options are removed in jdk9. Remove this code for jdk10.
static AliasedFlag const removed_develop_logging_flags[] = {
  { "TraceClassInitialization",   "-Xlog:class+init" },
  { "TraceClassLoaderData",       "-Xlog:class+loader+data" },
  { "TraceDefaultMethods",        "-Xlog:defaultmethods=debug" },
  { "TraceItables",               "-Xlog:itables=debug" },
  { "TraceMonitorMismatch",       "-Xlog:monitormismatch=info" },
  { "TraceSafepoint",             "-Xlog:safepoint=debug" },
  { "TraceStartupTime",           "-Xlog:startuptime" },
  { "TraceVMOperation",           "-Xlog:vmoperation=debug" },
  { "PrintVtables",               "-Xlog:vtables=debug" },
  { "VerboseVerification",        "-Xlog:verification" },
  { NULL, NULL }
};
#endif //PRODUCT
----
====


=== Building a unified logging tag reference

Ok nice, but `java -Xlog:help` list a lot more available tags than those already mentioned.

The issue with unified logging is the documentation, identifying the tag we want
can be tedious. If I select the tag `dump` what will it output and when, is it about heap dump.
Same if I select `system` is it about system calls, or else. Well it turns out there's just
no documentation whatsoever, you need to look at the code.


The starting point for this job was https://github.com/AdoptOpenJDK/openjdk-jdk11u/commit/d724e8a3489f8ebb57c7bbf82784a2b2d537fdc8[this commit]
and what the JEP-158 proposed :

.JEP-158
____
*JVM interface*

In the JVM a set of macros will be created with an API similar to:

[source]
----
log_<level>(Tag1[,...])(fmtstr, ...)
    syntax for the log macro
----

*Example:*

[source]
----
log_info(gc, rt, classloading)("Loaded %d objects.", object_count)
    the macro is checking the log level to avoid uneccessary
    calls and allocations.

log_debug(svc, debugger)("Debugger interface listening at port %d.", port_number)
----

____


The idea of this section is to _build_ a logging tag reference. For that
I needed grep and the hotspot repo. I build this reference on the code found in
11.0.7, but I don't think there was any change in 11.0.8; please keep in mind this is
only a snapshot and it's likely that tags get added or changed in later JVM revisions.

In the commit above there's an interesting file
https://github.com/corretto/corretto-11/blob/2750418af3603bcb10ba5e933a7198f21b78361d/src/src/hotspot/share/logging/logTag.hpp[src/hotspot/share/logging/logTag.hpp]
that declares all logging tags (138 in total). From there I searched where these tags where used.

.Log tags
[%autowidth.stretch,cols="m,a,3a"]
|===

| add                   | `redefine`                     |
| age                   | `gc`                           |
| alloc                 | `gc`                           | GC region or space allocation
| annotation            | `redefine`                     |
| aot                   | `aot`                          | Ahead of time logs
| arguments             |                                | JVM options warnings or errors (only errors, unless level is `trace`)
| attach                |                                | JVM attachment listener
| barrier               | `gc`,xxx                       | GC Write barrier coverage
| biasedlocking         |                                | Biased Locking mechanism https://github.com/corretto/corretto-11/blob/8bb50b6fcf0613dc85010c45f96fa048ecd5dba4/src/src/hotspot/share/runtime/biasedLocking.hpp[src/hotspot/share/runtime/biasedLocking.hpp]
| blocks                | `oopstorage`, `gc`             |
| bot                   | `gc`                           | Block Offset Table (side data structure with offset information indicating how far back the GC needs to go to find the beginning of an object).
| breakpoint            | `jvmti` (Redefinition)         | Part of the JVMTI, but logged under `redefine` prefix.
| bytecode              | `jfr`                          |
| cds                   | `cds`                          | Class Data Sharing logs
| census                | `gc`                           | CMS log about `freelist` information.
| class                 | `class`,aot                    | Class related information
| classhisto            | `gc`                           |
| cleanup               | `safepoint`                    | Safepoint cleaning information
| codecache             | `codecache`, `compilation`     | code cache for generated code: compiled java methods, runtime stubs, transition frames, etc. Segregated in 3 heaps (Non-nmethods like Buffers, Adapters and Runtime Stubs, nmethods that are profiled, nmethods that are not profiled). https://github.com/corretto/corretto-11/blob/2b351313740f148597cf680d8443df93931de813/src/src/hotspot/share/code/codeCache.cpp[src/hotspot/share/code/codeCache.cpp]
| compaction            | `gc`                           | GC compaction for G1GC and Parallel
| compilation           | `compilation`, `jit`           | Compilation
| constantpool          | `class`, `redefine`            | Constant pool, logged mostly during `redefine`
| constraints           | `class`                        | Class loader constraints
| container             | `OS`                           | Container (CGroup) related (`cpu`, `cpuset`, `memory`, `mountinfo`, ...)
| coops                 | `gc`                           | Compressed ordinary object pointers
| cpu                   | `gc`, `os`                     | CPU features when logged with `os`, CPU time ith `gc`
| cset                  | `gc`                           | Collection Set in G1
| data                  | `class`                        | Classloader data (allocation space, or metaspace)
| datacreation          | `perf`                         | Related to perf data creation
| dcmd                  | `jfr`                          | Diagnostic command, apparently only prefixed by `jfr`
| decoder               |                                | Related to ELF decoding (Executable and Linkable Format)
| defaultmethods        |                                | Runtime support for default method. Part of classes, but logged as a standalone tag.
| director              | `gc`                           | Related to ZGC
| dump                  | `redefine`                     |
| ergo                  | `gc`                           | Ergonomics, usually prefixes by `gc`, but can be found alone (e.g. for 2 logs about thread local handshakes)
| event                 | `jfr`                          | About JFR events
| exceptions            |                                | About Java exceptions handling in different parts (interpreter, during safepoint, compiler, ...). Specific exception handling during redefinition when prefixed by `redefine`.
| exit                  | `gc`                           | GC/heap related information after GC. `LogStreamHandle(Debug, gc, heap, exit) lsh;` https://github.com/corretto/corretto-11/blob/caa2f4cad666b508a88b92db01054ace8647a820/src/src/hotspot/share/gc/shared/genCollectedHeap.cpp[src/hotspot/share/gc/shared/genCollectedHeap.cpp]
| fingerprint           | `class`, `aot`                 | Class fingerprinting
| free                  | `malloc`                       | Log any C stdlib `malloc`, `realloc` or `free` calls, always logged via `malloc, free` tags.
| freelist              | `gc`                           | Chunks of memory that are supposed to be free, for CMS and metaspace
| gc                    | `gc`                           | GC log prefix
| handshake             | `thread`                       | Thread local handshakes https://github.com/corretto/corretto-11/blob/8bb50b6fcf0613dc85010c45f96fa048ecd5dba4/src/src/hotspot/share/runtime/handshake.hpp#L35-L39[src/hotspot/share/runtime/handshake.hpp]
| hashtables            |                                | When standalone, it's the internal bucketed hash table, far cousin of a `HashMap`, Hotspot uses it for strings, and other symbols. CDS uses another internal implementation for statistics, hence this tag may be prefixed by `cds`.
| heap                  | `gc`                           | Various GC heap related logs
| humongous             | `gc`                           | Humongous objects in G1GC
| ihop                  | `gc`                           | Heap occupancy (initial, current, target) in G1GC
| iklass                | `class`, `redefine`            | Internal class instance representation, logged prefixes `redefine`, `classes`
| init                  | `gc`, `class`                  | Mostly about class initialization when prefixed by `class`. About ZGC initialization when prefixed by `gc`.
| inlining              | `jit`                          | Method inlining information
| interpreter           | `interpreter`                  | Interpreter logs, only logs with `oopmap` and `safepoint` sub-tags.
| itables               |                                | JVM virtual call mechanism for interface calls, during JVM development (non-product build needed). Also see `vtables` tag. https://wiki.openjdk.java.net/display/HotSpot/InterfaceCalls[Hotspot wiki, title=Interface calls]
| jfr                   | `jfr`                          | JDK Flight Recorder
| jit                   | `jit`                          | Logs about method `inlining` and `compilation`
| jni                   | `gc`                           | Only logged during _GC locker_.
| jvmti                 | `jvmti`                        |
| liveness              | `gc`                           | G1GC region liveness (dead objects vs live objects)
| load                  | `gc`, `class`                  | Trace all classes loaded
| loader                | `class`                        | Class loader `data` and `constraints`
| logging               |                                | About unified logging
| malloc                | `malloc`                       | Log any C stdlib `malloc`, `realloc` or `free` calls, always logged via `malloc, free` tags.
| mark                  | `redefine`                     | Mark `obsolete` method during `redefine`
| marking               | `gc`                           | Marking information for G1GC, CMS, ZGC
| membername            |                                | Hashtable used by redefinition to replace methods. Used in conjunction with `table`, but without `redefine` prefix.
| memops                | `perf`                         | Memory operation logs `initialize` and `mmap_attach_shared`
| metadata              | `jfr`, `redefine`              | Logs about class redefinition, or logs about JFR metadata (although I didn't found any jfr logs in the codebase)
| metaspace             | `gc`                           | Logs about the metaspace memory space
| methodcomparator      | `redefinition`                 | Logs about method equivalence during redefinition.
| mirror                | `cds`                          | Logs about `cds` processing of class mirror. A java mirror is an instance of a `java.lang.Class`.
| mmu                   | `gc`                           | _Minimum Mutator Utilization_ is the (time) goal of GC work for G1GC and ZGC. G1GC defines this as a pause time goal (`MaxGCPauseMillis`) over a time slice (`GCPauseIntervalMillis`).
| module                |                                | Module system
| monitorinflation      |                                | Runtime synchronization support
| monitormismatch       |                                | Monitor matching failures during OopMapGeneration
| nestmates             | `class`                        | Nestmate logging
| nmethod               | `gc`, `class`, `redefine`      | native methods (as in compiled code versions of Java methods) logs in various subsystems: `gc`, `class`, `redefine`
| normalize             | `redefine`                     | Logs after method addition,deletion,replacement during redefinition
| objecttagging         | `jvmti`                        | JVMTI object tagging calls
| obsolete              | `redefine`                     | Obsolete method entry mainly for redefinition (and JVMTI)
| oldobject             | `jfr`                          | Old object sampling, currently only logging that sample was skipped due to lock contention.
| oom                   | `gc`                           | Reported when `metaspace` is out of memory.
| oopmap                | `interpreter`, `redefine`      | Ordinary Object Pointer caching logs, prefixed by `interpreter` and `redefine`.
| oops                  | `gc`                           | Ordinary Object Pointers logs in CMS and ZGC
| oopstorage            |                                | Internal off-heap data structure for management of references to objects allocated in the Java heap
| os                    | `OS`                           | Operating System interactions logs.
| pagesize              |                                | Logs about page size. Not prefixed by `os`.
| parser                | `jfr`                          | Part of jfr, but log instructions found in the code base.
| patch                 | `module`                       | Logging `--patch-module`
| path                  | `class`                        | Class path or module path processing
| perf                  | `perf`                         | Logs about JVM perf counters, when prefixed by `stringtable` it's about interned strings (`String.intern()`).
| phases                | `gc`                           | Logs that is part of phase of a GC, in particular for ZGC and G1GC.
| plab                  | `gc`                           | Logs about per-GC-thread allocation buffer, those are used during GC to prevent thread competition on the same memory space.
| preorder              | `class`                        | Trace all classes loaded in order referenced (not loaded)
| preview               |                                | Trace loading of preview feature types
| promotion             | `gc`                           | Object promotion logs during GC.
| protectiondomain      | `class`                        | Class protection domain verification.
| purge                 | `redefine`                     | Logs about previous class version unloading during redefinition
| redefine              | `redefine`                     | Class redefinition sub-subsystem, in particular for JVMTI (e.g. when debugging) and with Java agent doing class transformation / re-transformation.
| ref                   | `gc`                           | GC object or class references related logs
| refine                | `gc`                           | G1GC logs about refinement threads of the RSet (Remembered set)
| region                | `gc`                           | G1GC logs about region. The `alloc` and `heap` tag prefixes at `debug` level will print region statistics. `trace` level logs the actions that the GC performs on a region.
| reloc                 | `gc`                           | ZGC object set relocation.
| remset                | `gc`                           | G1GC remembered set. The `tracking` and `exit` tag can come along if level is `trace`.
| resolve               | `class`,aot                    | Logs about constant pool resolutions, e.g. when loading classes, lambdas, doing reflection, jni
| safepoint             | `safepoint`                    | JVM stop-the-world operations Heap Dump, some GC tasks, deoptimization, revokebias, library loading, etc... (https://github.com/corretto/corretto-11/blob/caa2f4cad666b508a88b92db01054ace8647a820/src/src/hotspot/share/runtime/vm_operations.hpp#L42-L134[src/hotspot/share/runtime/vm_operations.hpp], the operation in this enum are not all in safepoint though). Specific operation logs can be logged with the standalone `vmoperation`.
| sampling              | `jfr`                          | Old object sampling in JFR. `trace` level only.
| scavenge              | `gc`                           | CMS, Parallel, and Serial GC scavenge traces.
| setting               | `jfr`                          | Part of jfr, but log instructions found in the code base.
| smr                   | `thread`                       | Thread Safe Memory Reclamation (Thread-SMR), https://en.wikipedia.org/wiki/Hazard_pointer[hazard pointers]. https://github.com/corretto/corretto-11/blob/8bb50b6fcf0613dc85010c45f96fa048ecd5dba4/src/src/hotspot/share/runtime/threadSMR.cpp[src/hotspot/share/runtime/threadSMR.cpp].
| stackmap              | `redefine`                     | Constant pool changes in method stackmap during redefinition
| stacktrace            |                                | Logged during `Throwable.fillInStackTrace()`.
| stackwalk             |                                | Logs when using `StackWalker`.
| start                 | `gc`, `codecache`              | Indicates a ZGC phase start, it's thus prefixed by `gc`, But can also indicate other operation start, like for `codecache`.
| startuptime           |                                | Logs the JVM subsystems startup time (interpreter, GC, module systems, class loading, aot, genesis which is about memory zones ...)
| state                 | `gc`                           | CMS GC states.
| stats                 | `gc`                           | GC stats logs. Also seen with (`oopstorage, blocks` tag prefixes).
| stringdedup           | `gc`                           | G1GC string deduplication (for old generation)
| stringtable           |                                | About interned strings (`String.intern()`), can be seen with the `gc` tag prefix when G1GC is in use to log string and symbol cleanups.
| subclass              | `class`, `redefine`            | Sub-class unloading. Affected subclasses during redefinition.
| survivor              | `gc`                           | CMS GC survivor informations.
| sweep                 | `gc`, `codecache`              | CMS GC sweeping activity. And codecache native methods flushing.
| system                | `jfr`                          | JFR system logging, recordind start/stop, emergency dump, etc.
| table                 | `membername`                   | Only used with `membername`, about the hashtable to record methods, and replace them during redefinition.
| task                  | `gc`                           | Mostly related to GC tasks, useful to see the `phases` tag. Also appears with `handshake` tag prefix for thread local handshakes.
| thread                | `os`                           | When used as a tag prefix, it's about `smr`, when the tag prefix is `os` it's about the thread lifecycle and guards.
| time                  | `gc`                           | Timed Parallel GC operations
| timer                 | `thread`, `redefine`           | Timed redefine operation, and thread exit
| tlab                  | `gc`                           | Thread local allocation buffers statistics (`trace`)
| tracking              | `gc`                           | G1GC remembered set tracking
| unload                | `class`                        | Class or module unloading
| unshareable           | `cds`                          | For classes that cannot be shared, especially interesting during CDS archive creation
| update                | `redefine`                     | Logs about redefinition changes in classes or methods.
| verification          |                                | Classes bytecode verification, when to tag prefix. Same for classes in CDS archive when prefixed by `cds`.
| verify                | `gc`                           | Verifications operations done during GC operations.
| vmoperation           |                                | Logs VM operations
| vmthread              |                                | JVM threads that perform the VM operations (usually during safepoints)
| vtables               |                                | Java's virtual calls mechanism (virtual table allows to find the right method address for the current instance in hierarchy of classes).
| vtablestubs           |                                | Java's virtual calls mechanism that is used for megamorphic call sites (i.e. when the method to execute is not the same on successive executions because the object hierarchy differ). Hotspot wiki https://wiki.openjdk.java.net/display/HotSpot/PerformanceTechniques[1,title=Performance technics] https://wiki.openjdk.java.net/display/HotSpot/VirtualCalls[2,title=Virtual calls]
| workgang              | `gc`                           | GC worker threads

|===


In building this reference we see that some JVM sub-systems can output a lot of logs.
Two subsystems stands out in the way they describe their tagsets : JFR and the Garbage Collection

.JFR prefixes
[%collapsible]
====
.https://github.com/corretto/corretto-11/blob/8bb50b6fcf0613dc85010c45f96fa048ecd5dba4/src/src/hotspot/share/jfr/utilities/jfrLogTagSets.hpp[src/hotspot/share/jfr/utilities/jfrLogTagSets.hpp]
[source, c++]
----
#define JFR_LOG_TAG_SET_LIST \
  JFR_LOG_TAG(jfr) \
  JFR_LOG_TAG(jfr, system) \
  JFR_LOG_TAG(jfr, system, event) \
  JFR_LOG_TAG(jfr, system, setting) \
  JFR_LOG_TAG(jfr, system, bytecode) \
  JFR_LOG_TAG(jfr, system, parser) \
  JFR_LOG_TAG(jfr, system, metadata) \
  JFR_LOG_TAG(jfr, metadata) \
  JFR_LOG_TAG(jfr, event) \
  JFR_LOG_TAG(jfr, setting) \
  JFR_LOG_TAG(jfr, dcmd)
  /* NEW TAGS, DONT FORGET TO UPDATE JAVA SIDE */
----

However note that the tags seen above are not all used, in particular those under `system`.
====

.GC prefixes
[%collapsible]
====
.https://github.com/corretto/corretto-11/blob/8bb50b6fcf0613dc85010c45f96fa048ecd5dba4/src/src/hotspot/share/logging/logPrefix.hpp#L45-L90[src/hotspot/share/logging/logPrefix.hpp#L45-L90]
[source, cpp]
----
#define LOG_PREFIX_LIST \
  LOG_PREFIX(GCId::print_prefix, LOG_TAGS(gc)) \
  LOG_PREFIX(GCId::print_prefix, LOG_TAGS(gc, age)) \
  LOG_PREFIX(GCId::print_prefix, LOG_TAGS(gc, alloc)) \
  LOG_PREFIX(GCId::print_prefix, LOG_TAGS(gc, alloc, region)) \
  LOG_PREFIX(GCId::print_prefix, LOG_TAGS(gc, barrier)) \
  LOG_PREFIX(GCId::print_prefix, LOG_TAGS(gc, classhisto)) \
  LOG_PREFIX(GCId::print_prefix, LOG_TAGS(gc, compaction)) \
  LOG_PREFIX(GCId::print_prefix, LOG_TAGS(gc, cpu)) \
  LOG_PREFIX(GCId::print_prefix, LOG_TAGS(gc, ergo)) \
  LOG_PREFIX(GCId::print_prefix, LOG_TAGS(gc, ergo, cset)) \
  LOG_PREFIX(GCId::print_prefix, LOG_TAGS(gc, ergo, heap)) \
  LOG_PREFIX(GCId::print_prefix, LOG_TAGS(gc, ergo, ihop)) \
  LOG_PREFIX(GCId::print_prefix, LOG_TAGS(gc, ergo, refine)) \
  LOG_PREFIX(GCId::print_prefix, LOG_TAGS(gc, heap)) \
  LOG_PREFIX(GCId::print_prefix, LOG_TAGS(gc, heap, region)) \
  LOG_PREFIX(GCId::print_prefix, LOG_TAGS(gc, freelist)) \
  LOG_PREFIX(GCId::print_prefix, LOG_TAGS(gc, humongous)) \
  LOG_PREFIX(GCId::print_prefix, LOG_TAGS(gc, ihop)) \
  LOG_PREFIX(GCId::print_prefix, LOG_TAGS(gc, liveness)) \
  LOG_PREFIX(GCId::print_prefix, LOG_TAGS(gc, load)) \
  LOG_PREFIX(GCId::print_prefix, LOG_TAGS(gc, marking)) \
  LOG_PREFIX(GCId::print_prefix, LOG_TAGS(gc, metaspace)) \
  LOG_PREFIX(GCId::print_prefix, LOG_TAGS(gc, mmu)) \
  LOG_PREFIX(GCId::print_prefix, LOG_TAGS(gc, nmethod)) \
  LOG_PREFIX(GCId::print_prefix, LOG_TAGS(gc, phases)) \
  LOG_PREFIX(GCId::print_prefix, LOG_TAGS(gc, phases, ref)) \
  LOG_PREFIX(GCId::print_prefix, LOG_TAGS(gc, phases, start)) \
  LOG_PREFIX(GCId::print_prefix, LOG_TAGS(gc, phases, task)) \
  LOG_PREFIX(GCId::print_prefix, LOG_TAGS(gc, plab)) \
  LOG_PREFIX(GCId::print_prefix, LOG_TAGS(gc, region)) \
  LOG_PREFIX(GCId::print_prefix, LOG_TAGS(gc, remset)) \
  LOG_PREFIX(GCId::print_prefix, LOG_TAGS(gc, remset, tracking)) \
  LOG_PREFIX(GCId::print_prefix, LOG_TAGS(gc, ref)) \
  LOG_PREFIX(GCId::print_prefix, LOG_TAGS(gc, ref, start)) \
  LOG_PREFIX(GCId::print_prefix, LOG_TAGS(gc, reloc)) \
  LOG_PREFIX(GCId::print_prefix, LOG_TAGS(gc, start)) \
  LOG_PREFIX(GCId::print_prefix, LOG_TAGS(gc, stringtable)) \
  LOG_PREFIX(GCId::print_prefix, LOG_TAGS(gc, sweep)) \
  LOG_PREFIX(GCId::print_prefix, LOG_TAGS(gc, task)) \
  LOG_PREFIX(GCId::print_prefix, LOG_TAGS(gc, task, start)) \
  LOG_PREFIX(GCId::print_prefix, LOG_TAGS(gc, task, stats)) \
  LOG_PREFIX(GCId::print_prefix, LOG_TAGS(gc, task, time)) \
  DEBUG_ONLY(LOG_PREFIX(Test_log_prefix_prefixer, LOG_TAGS(logging, test))) \
  LOG_PREFIX(GCId::print_prefix, LOG_TAGS(gc, tlab)) \
  LOG_PREFIX(GCId::print_prefix, LOG_TAGS(gc, workgang))
----
====

The other tagset or prefixes are not declared, so I rebuilt them in a non exhaustive way.

.AOT https://github.com/corretto/corretto-11/blob/2b351313740f148597cf680d8443df93931de813/src/src/hotspot/share/aot/aotCodeHeap.cpp[src/hotspot/share/aot/aotCodeHeap.cpp]
* `log_debug(aot, class, resolve)`
* `log_info(aot, class, resolve)`
* `log_trace(aot, class, fingerprint)`
* `log_trace(aot, class, load)`


.Classes
Class file loading, linking::
* `log_error(class)` https://github.com/corretto/corretto-11/blob/caa2f4cad666b508a88b92db01054ace8647a820/src/src/hotspot/share/classfile/javaClasses.cpp[src/hotspot/share/classfile/javaClasses.cpp]
* `log_info(class, fingerprint)` https://github.com/corretto/corretto-11/blob/2b351313740f148597cf680d8443df93931de813/src/src/hotspot/share/classfile/classFileParser.cpp[src/hotspot/share/classfile/classFileParser.cpp]
* `log_info(class, preview)` https://github.com/corretto/corretto-11/blob/2b351313740f148597cf680d8443df93931de813/src/src/hotspot/share/classfile/classFileParser.cpp[src/hotspot/share/classfile/classFileParser.cpp]
* `log_debug(class, resolve)` https://github.com/corretto/corretto-11/blob/2b351313740f148597cf680d8443df93931de813/src/src/hotspot/share/classfile/classFileParser.cpp[src/hotspot/share/classfile/classFileParser.cpp]

* `LogMessage(class, load)` https://github.com/corretto/corretto-11/blob/caa2f4cad666b508a88b92db01054ace8647a820/src/src/hotspot/share/oops/instanceKlass.cpp[src/hotspot/share/oops/instanceKlass.cpp]
* `log_trace(class, nestmates)` https://github.com/corretto/corretto-11/blob/caa2f4cad666b508a88b92db01054ace8647a820/src/src/hotspot/share/oops/instanceKlass.cpp[src/hotspot/share/oops/instanceKlass.cpp]
* `LogTarget(Info, class, init)` https://github.com/corretto/corretto-11/blob/caa2f4cad666b508a88b92db01054ace8647a820/src/src/hotspot/share/oops/instanceKlass.cpp[src/hotspot/share/oops/instanceKlass.cpp]
* `log_trace(class, fingerprint)` https://github.com/corretto/corretto-11/blob/caa2f4cad666b508a88b92db01054ace8647a820/src/src/hotspot/share/oops/instanceKlass.cpp[src/hotspot/share/oops/instanceKlass.cpp]

* `LogTarget(Debug, class, loader, data)` https://github.com/corretto/corretto-11/blob/caa2f4cad666b508a88b92db01054ace8647a820/src/src/hotspot/share/classfile/classLoaderData.cpp[src/hotspot/share/classfile/classLoaderData.cpp]
* `LogTarget(Trace, class, loader, data)` https://github.com/corretto/corretto-11/blob/caa2f4cad666b508a88b92db01054ace8647a820/src/src/hotspot/share/classfile/classLoaderData.cpp[src/hotspot/share/classfile/classLoaderData.cpp]
* `log_debug(class, loader, data)` https://github.com/corretto/corretto-11/blob/caa2f4cad666b508a88b92db01054ace8647a820/src/src/hotspot/share/classfile/classLoaderData.cpp[src/hotspot/share/classfile/classLoaderData.cpp]

* `log_info(class, load)` https://github.com/corretto/corretto-11/blob/0fb85ec862711e6daa4db7d7fab819c0e7a1273d/src/src/hotspot/share/classfile/classLoader.cpp[src/hotspot/share/classfile/classLoader.cpp]
* `log_info(class, path)` https://github.com/corretto/corretto-11/blob/0fb85ec862711e6daa4db7d7fab819c0e7a1273d/src/src/hotspot/share/classfile/classLoader.cpp[src/hotspot/share/classfile/classLoader.cpp]

* `LogTarget(Info, class, loader, constraints)` https://github.com/corretto/corretto-11/blob/8bb50b6fcf0613dc85010c45f96fa048ecd5dba4/src/src/hotspot/share/classfile/loaderConstraints.cpp[src/hotspot/share/classfile/loaderConstraints.cpp]

* `log_debug(class, init)` https://github.com/corretto/corretto-11/blob/2b351313740f148597cf680d8443df93931de813/src/src/hotspot/share/classfile/verifier.cpp[src/hotspot/share/classfile/verifier.cpp]
* `log_debug(class, resolve)` https://github.com/corretto/corretto-11/blob/2b351313740f148597cf680d8443df93931de813/src/src/hotspot/share/classfile/verifier.cpp[src/hotspot/share/classfile/verifier.cpp]
* `log_info(verification)` https://github.com/corretto/corretto-11/blob/2b351313740f148597cf680d8443df93931de813/src/src/hotspot/share/classfile/verifier.cpp[src/hotspot/share/classfile/verifier.cpp]

Class loding service::
* `log_info(class, unload)` https://github.com/corretto/corretto-11/blob/8bb50b6fcf0613dc85010c45f96fa048ecd5dba4/src/src/hotspot/share/services/classLoadingService.cpp[src/hotspot/share/services/classLoadingService.cpp]

Constant Pool::
* `log_debug(class, resolve)` https://github.com/corretto/corretto-11/blob/2b351313740f148597cf680d8443df93931de813/src/src/hotspot/share/oops/constantPool.cpp[src/hotspot/share/oops/constantPool.cpp]

Native methods (compiled code versions of Java methods)::
* `LogTarget(Trace, class, unload, nmethod)` https://github.com/corretto/corretto-11/blob/caa2f4cad666b508a88b92db01054ace8647a820/src/src/hotspot/share/code/nmethod.cpp[src/hotspot/share/code/nmethod.cpp]

Memory::
* `log_info(class, path)` https://github.com/corretto/corretto-11/blob/6887ddf929a1baae5b4f73a3b6c255c4ee942f7c/src/src/hotspot/share/memory/filemap.cpp[src/hotspot/share/memory/filemap.cpp]

OOPS::
* `log_trace(class, unload)` https://github.com/corretto/corretto-11/blob/2b351313740f148597cf680d8443df93931de813/src/src/hotspot/share/oops/klass.cpp[src/hotspot/share/oops/klass.cpp]

JNI::
* `log_is_enabled(Debug, class, resolve)` https://github.com/corretto/corretto-11/blob/caa2f4cad666b508a88b92db01054ace8647a820/src/src/hotspot/share/prims/jni.cpp[src/hotspot/share/prims/jni.cpp]
+
`log_debug(class, resolve)` https://github.com/corretto/corretto-11/blob/2b351313740f148597cf680d8443df93931de813/src/src/hotspot/share/prims/jvm.cpp[src/hotspot/share/prims/jvm.cpp]

Reflection::
* `log_debug(class, resolve)` https://github.com/corretto/corretto-11/blob/caa2f4cad666b508a88b92db01054ace8647a820/src/src/hotspot/share/runtime/reflection.cpp[src/hotspot/share/runtime/reflection.cpp]


.Class Data Sharing
* `log_info(cds)` https://github.com/corretto/corretto-11/blob/6887ddf929a1baae5b4f73a3b6c255c4ee942f7c/src/src/hotspot/share/memory/filemap.cpp[src/hotspot/share/memory/filemap.cpp]
* `log_trace(cds)` https://github.com/corretto/corretto-11/blob/2b351313740f148597cf680d8443df93931de813/src/src/hotspot/share/oops/klass.cpp[src/hotspot/share/oops/klass.cpp]
* `log_trace(cds, unshareable)` https://github.com/corretto/corretto-11/blob/2b351313740f148597cf680d8443df93931de813/src/src/hotspot/share/oops/klass.cpp[src/hotspot/share/oops/klass.cpp]
* `log_debug(cds, mirror)` https://github.com/corretto/corretto-11/blob/2b351313740f148597cf680d8443df93931de813/src/src/hotspot/share/oops/klass.cpp[src/hotspot/share/oops/klass.cpp]
* `log_trace(cds)` https://github.com/corretto/corretto-11/blob/2b351313740f148597cf680d8443df93931de813/src/src/hotspot/share/oops/constantPool.cpp[src/hotspot/share/oops/constantPool.cpp]

.Redefinition
* Native methods (compiled code versions of Java methods)
** `log_debug(redefine, class, nmethod)` https://github.com/corretto/corretto-11/blob/caa2f4cad666b508a88b92db01054ace8647a820/src/src/hotspot/share/code/nmethod.cpp[src/hotspot/share/code/nmethod.cpp]

* Interpreter
** `log_debug(redefine, class, interpreter, oopmap)` https://github.com/corretto/corretto-11/blob/8bb50b6fcf0613dc85010c45f96fa048ecd5dba4/src/src/hotspot/share/interpreter/oopMapCache.cpp[src/hotspot/share/interpreter/oopMapCache.cpp]


.Compilation, Just-in-Time
* `Log(compilation, codecache) log; if(log.is_debug())`  https://github.com/corretto/corretto-11/blob/caa2f4cad666b508a88b92db01054ace8647a820/src/src/hotspot/share/compiler/compileBroker.cpp[src/hotspot/share/compiler/compileBroker.cpp]
* `LogTarget(Debug, jit, compilation)` https://github.com/corretto/corretto-11/blob/2b351313740f148597cf680d8443df93931de813/src/src/hotspot/share/compiler/compileTask.cpp[src/hotspot/share/compiler/compileTask.cpp]
* ``
* ``

* `log_debug(interpreter, oopmap)` https://github.com/corretto/corretto-11/blob/8bb50b6fcf0613dc85010c45f96fa048ecd5dba4/src/src/hotspot/share/interpreter/oopMapCache.cpp[src/hotspot/share/interpreter/oopMapCache.cpp]


.Java Virtual Machine Tool Interface (JVMTI, JSR-163)



=== Tags combinations examples

==== OS and container related

If the workload you are working on is running on containers you may have heard of the
os and container tags :

.os, container, pagesize logs
[source, shell]
----
$ head -n 200 /var/log/2020-05-22_22-28-32-os-container-pagezise.log
[0.003s][trace][os,container] OSContainer::init: Initializing Container Support
[0.003s][trace][os,container] Path to /memory.use_hierarchy is /sys/fs/cgroup/memory/memory.use_hierarchy
[0.003s][trace][os,container] Use Hierarchy is: 1
[0.003s][trace][os,container] Path to /memory.limit_in_bytes is /sys/fs/cgroup/memory/memory.limit_in_bytes
[0.003s][trace][os,container] Memory Limit is: 5368709120
[0.003s][info ][os,container] Memory Limit is: 5368709120
[0.003s][trace][os,container] Path to /cpu.cfs_quota_us is /sys/fs/cgroup/cpu/cpu.cfs_quota_us
[0.003s][trace][os,container] CPU Quota is: -1
[0.003s][trace][os,container] Path to /cpu.cfs_period_us is /sys/fs/cgroup/cpu/cpu.cfs_period_us
[0.003s][trace][os,container] CPU Period is: 100000
[0.003s][trace][os,container] Path to /cpu.shares is /sys/fs/cgroup/cpu/cpu.shares
[0.004s][trace][os,container] CPU Shares is: 1024
[0.004s][trace][os,container] OSContainer::active_processor_count: 4
[0.004s][trace][os,container] Path to /cpu.cfs_quota_us is /sys/fs/cgroup/cpu/cpu.cfs_quota_us
[0.004s][trace][os,container] CPU Quota is: -1
[0.004s][trace][os,container] Path to /cpu.cfs_period_us is /sys/fs/cgroup/cpu/cpu.cfs_period_us
[0.004s][trace][os,container] CPU Period is: 100000
[0.004s][trace][os,container] Path to /cpu.shares is /sys/fs/cgroup/cpu/cpu.shares
[0.004s][trace][os,container] CPU Shares is: 1024
[0.004s][trace][os,container] OSContainer::active_processor_count: 4
[0.004s][info ][os          ] Use of CLOCK_MONOTONIC is supported
[0.004s][info ][os          ] Use of pthread_condattr_setclock is supported
[0.004s][info ][os          ] Relative timed-wait using pthread_cond_timedwait is associated with CLOCK_MONOTONIC
[0.004s][info ][os          ] HotSpot is running with glibc 2.28, NPTL 2.28
[0.005s][info ][os          ] SafePoint Polling address, bad (protected) page:0x00007fa25e8ee000, good (unprotected) page:0x00007fa25e8ef000
[0.005s][info ][os          ] attempting shared library load of /usr/lib/jvm/java-11-amazon-corretto/lib/libinstrument.so
[0.005s][info ][os          ] shared library load of /usr/lib/jvm/java-11-amazon-corretto/lib/libinstrument.so was successful
[0.005s][info ][os          ] attempting shared library load of /usr/lib/jvm/java-11-amazon-corretto/lib/libinstrument.so
[0.005s][info ][os          ] shared library load of /usr/lib/jvm/java-11-amazon-corretto/lib/libinstrument.so was successful
[0.006s][info ][os          ] attempting shared library load of /usr/lib/jvm/java-11-amazon-corretto/lib/libinstrument.so
[0.006s][info ][os          ] shared library load of /usr/lib/jvm/java-11-amazon-corretto/lib/libinstrument.so was successful
[0.008s][info ][os,thread   ] Thread attached (tid: 8, pthread id: 140335320479488).
[0.008s][info ][os          ] attempting shared library load of /usr/lib/jvm/java-11-amazon-corretto/lib/libzip.so
[0.008s][info ][os          ] shared library load of /usr/lib/jvm/java-11-amazon-corretto/lib/libzip.so was successful
[0.008s][info ][os          ] attempting shared library load of /usr/lib/jvm/java-11-amazon-corretto/lib/libjimage.so
[0.008s][info ][os          ] shared library load of /usr/lib/jvm/java-11-amazon-corretto/lib/libjimage.so was successful
[0.008s][trace][os,container] Path to /cpu.cfs_quota_us is /sys/fs/cgroup/cpu/cpu.cfs_quota_us
[0.008s][trace][os,container] CPU Quota is: -1
[0.008s][trace][os,container] Path to /cpu.cfs_period_us is /sys/fs/cgroup/cpu/cpu.cfs_period_us
[0.008s][trace][os,container] CPU Period is: 100000
[0.008s][trace][os,container] Path to /cpu.shares is /sys/fs/cgroup/cpu/cpu.shares
[0.008s][trace][os,container] CPU Shares is: 1024
[0.009s][trace][os,container] OSContainer::active_processor_count: 4
[0.009s][info ][pagesize    ] CodeHeap 'non-nmethods':  min=2496K max=5696K base=0x00007fa24090d000 page_size=4K size=5696K
[0.009s][info ][pagesize    ] CodeHeap 'profiled nmethods':  min=2496K max=120032K base=0x00007fa240e9d000 page_size=4K size=120032K
[0.009s][info ][pagesize    ] CodeHeap 'non-profiled nmethods':  min=2496K max=120032K base=0x00007fa2483d5000 page_size=4K size=120032K
[0.010s][info ][os,cpu      ] CPU:total 4 (initial active 4) (1 cores per cpu, 1 threads per core) family 6 model 142 stepping 10, cmov, cx8, fxsr, mmx, sse, sse2, sse3, ssse3, sse4.1, sse4.2, popcnt, avx, avx2, aes, clmul, erms, 3dnowpref, lzcnt, tsc, tscinvbit, bmi1, bmi2, fma
[0.010s][info ][os,cpu      ] CPU Model and flags from /proc/cpuinfo:
[0.010s][info ][os,cpu      ] model name  : Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz
[0.010s][info ][os,cpu      ] flags               : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht pbe syscall nx pdpe1gb lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq dtes64 ds_cpl ssse3 sdbg fma cx16 xtpr pcid sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch pti fsgsbase bmi1 avx2 bmi2 erms xsaveopt arat
[0.010s][info ][os,thread   ] Thread started (pthread id: 140335306258176, attributes: stacksize: 1024k, guardsize: 4k, detached).
[0.010s][info ][os,thread   ] Thread is alive (tid: 9, pthread id: 140335306258176).
[0.011s][info ][pagesize    ] Heap:  min=8M max=768M base=0x00000000d0000000 page_size=4K size=768M
[0.011s][info ][pagesize    ] Block Offset Table: req_size=1536K base=0x00007fa240389000 page_size=4K alignment=4K size=1536K
[0.011s][info ][pagesize    ] Card Table: req_size=1536K base=0x00007fa240209000 page_size=4K alignment=4K size=1536K
[0.011s][info ][pagesize    ] Card Counts Table: req_size=1536K base=0x00007fa240089000 page_size=4K alignment=4K size=1536K
[0.011s][info ][pagesize    ] Prev Bitmap: req_size=12M base=0x00007fa23b400000 page_size=4K alignment=4K size=12M
[0.011s][info ][pagesize    ] Next Bitmap: req_size=12M base=0x00007fa23a800000 page_size=4K alignment=4K size=12M
[0.011s][info ][os,thread   ] Thread started (pthread id: 140334742894336, attributes: stacksize: 1024k, guardsize: 4k, detached).
[0.011s][info ][os,thread   ] Thread is alive (tid: 10, pthread id: 140334742894336).
[0.011s][info ][os,thread   ] Thread started (pthread id: 140334741837568, attributes: stacksize: 1024k, guardsize: 4k, detached).
[0.011s][info ][os,thread   ] Thread is alive (tid: 11, pthread id: 140334741837568).
[0.012s][info ][os,thread   ] Thread started (pthread id: 140334703015680, attributes: stacksize: 1024k, guardsize: 4k, detached).
[0.012s][info ][os,thread   ] Thread is alive (tid: 12, pthread id: 140334703015680).
[0.012s][info ][os,thread   ] Thread started (pthread id: 140334499624704, attributes: stacksize: 1024k, guardsize: 4k, detached).
[0.012s][info ][os,thread   ] Thread is alive (tid: 13, pthread id: 140334499624704).
[0.021s][info ][os,thread   ] Thread started (pthread id: 140334490179328, attributes: stacksize: 1024k, guardsize: 4k, detached).
[0.021s][info ][os,thread   ] Thread is alive (tid: 14, pthread id: 140334490179328).
[0.024s][trace][os,container] Path to /cpu.cfs_quota_us is /sys/fs/cgroup/cpu/cpu.cfs_quota_us
[0.024s][trace][os,container] CPU Quota is: -1
[0.024s][trace][os,container] Path to /cpu.cfs_period_us is /sys/fs/cgroup/cpu/cpu.cfs_period_us
[0.024s][trace][os,container] CPU Period is: 100000
[0.024s][trace][os,container] Path to /cpu.shares is /sys/fs/cgroup/cpu/cpu.shares
[0.024s][trace][os,container] CPU Shares is: 1024
[0.024s][trace][os,container] OSContainer::active_processor_count: 4
[0.025s][info ][os,thread   ] Thread started (pthread id: 140334489122560, attributes: stacksize: 1024k, guardsize: 0k, detached).
[0.025s][info ][os,thread   ] Thread is alive (tid: 15, pthread id: 140334489122560).
[0.025s][info ][os,thread   ] Thread started (pthread id: 140334488069888, attributes: stacksize: 1024k, guardsize: 0k, detached).
[0.025s][info ][os,thread   ] Thread is alive (tid: 16, pthread id: 140334488069888).
[0.033s][info ][os,thread   ] Thread started (pthread id: 140334485497600, attributes: stacksize: 1024k, guardsize: 0k, detached).
[0.033s][info ][os,thread   ] Thread is alive (tid: 17, pthread id: 140334485497600).
[0.033s][info ][os,thread   ] Thread started (pthread id: 140334484444928, attributes: stacksize: 1024k, guardsize: 0k, detached).
[0.033s][info ][os,thread   ] Thread is alive (tid: 18, pthread id: 140334484444928).
[0.033s][info ][os,thread   ] Thread started (pthread id: 140334483392256, attributes: stacksize: 1024k, guardsize: 0k, detached).
[0.034s][info ][os,thread   ] Thread is alive (tid: 19, pthread id: 140334483392256).
[0.034s][info ][os,thread   ] Thread started (pthread id: 140334482339584, attributes: stacksize: 1024k, guardsize: 0k, detached).
[0.035s][info ][os,thread   ] Thread is alive (tid: 20, pthread id: 140334482339584).
[0.036s][trace][os,container] Path to /memory.limit_in_bytes is /sys/fs/cgroup/memory/memory.limit_in_bytes
[0.036s][trace][os,container] Memory Limit is: 5368709120
[0.036s][trace][os,container] Path to /memory.usage_in_bytes is /sys/fs/cgroup/memory/memory.usage_in_bytes
[0.036s][trace][os,container] Memory Usage is: 9551872
[0.037s][trace][os,container] Path to /memory.usage_in_bytes is /sys/fs/cgroup/memory/memory.usage_in_bytes
[0.037s][trace][os,container] Memory Usage is: 9682944
...
[0.058s][trace][os,container] Path to /memory.limit_in_bytes is /sys/fs/cgroup/memory/memory.limit_in_bytes
[0.058s][trace][os,container] Memory Limit is: 5368709120
[0.058s][trace][os,container] Path to /memory.usage_in_bytes is /sys/fs/cgroup/memory/memory.usage_in_bytes
[0.058s][trace][os,container] Memory Usage is: 12820480
...
[0.064s][info ][os,thread   ] Thread started (pthread id: 140334481286912, attributes: stacksize: 1024k, guardsize: 0k, detached).
[0.064s][info ][os,thread   ] Thread is alive (tid: 21, pthread id: 140334481286912).
...
[8005.132s][trace][os,container] Path to /memory.limit_in_bytes is /sys/fs/cgroup/memory/memory.limit_in_bytes
[8005.132s][trace][os,container] Memory Limit is: 5368709120
[8005.132s][trace][os,container] Path to /memory.usage_in_bytes is /sys/fs/cgroup/memory/memory.usage_in_bytes
[8005.132s][trace][os,container] Memory Usage is: 4093734912
[8014.238s][trace][os,container] Path to /memory.limit_in_bytes is /sys/fs/cgroup/memory/memory.limit_in_bytes
[8014.238s][trace][os,container] Memory Limit is: 5368709120
[8014.238s][trace][os,container] Path to /memory.usage_in_bytes is /sys/fs/cgroup/memory/memory.usage_in_bytes
[8014.238s][trace][os,container] Memory Usage is: 4093943808
...
----


==== Class redefinition

[source,java]
----
public class AgentTest {

    public static void main(String[] args) {
        Foo foo = new Foo();
        System.out.printf("[%.3fs][stdout] m(): %s%n",
                          ManagementFactory.getRuntimeMXBean().getUptime() / 1000d,
                          foo.m());

        ByteBuddyAgent.install();
        new ByteBuddy()
                .redefine(Bar.class)
                .name(Foo.class.getName())
                .make()
                .load(Foo.class.getClassLoader(), ClassReloadingStrategy.fromInstalledAgent());

        System.out.printf("[%.3fs][stdout] m(): %s%n",
                          ManagementFactory.getRuntimeMXBean().getUptime() / 1000d,
                          foo.m());
    }

    private static class Foo {
        String m() { return "foo"; }
    }
    private static class Bar {
        String m() { return "bar"; }
    }
}
----



[source, shell]
----
$ java -Xlog:redefine+class*=debug -cp .:./lib/byte-buddy-agent-1.10.13.jar:./lib/byte-buddy-1.10.13.jar AgentTest
[0.151s][stdout] m(): foo
[0.688s][debug][redefine,class,load] loading name=AgentTest$Foo kind=101 (avail_mem=108304K)
[0.688s][info ][redefine,class,constantpool] old_cp_len=25, scratch_cp_len=29
[0.688s][debug][redefine,class,constantpool] after pass 0: merge_cp_len=25
[0.688s][debug][redefine,class,constantpool] after pass 1a: merge_cp_len=31, scratch_i=25, index_map_len=6
[0.688s][debug][redefine,class,constantpool] after pass 1b: merge_cp_len=31, scratch_i=29, index_map_len=10
[0.688s][info ][redefine,class,constantpool] merge_cp_len=31, index_map_len=10
[0.688s][debug][redefine,class,load        ] loaded name=AgentTest$Foo (avail_mem=108304K)
[0.690s][info ][redefine,class,update      ] adjust: name=AgentTest$Foo
[0.690s][debug][redefine,class,update,constantpool] cpc special, static or dynamic entry update: <init>(()V)
[0.690s][info ][redefine,class,load               ] redefined name=AgentTest$Foo, count=1 (avail_mem=108304K)
[0.690s][info ][redefine,class,timer              ] vm_op: all=0  prologue=0  doit=0
[0.690s][info ][redefine,class,timer              ] redefine_single_class: phase1=0  phase2=0
[0.690s][stdout] m(): bar
----

