---
authors: ["brice.dutheil"]
date: "2020-05-24T01:54:58+02:00"
language: en
draft: true
#tags: ["jfr","profiling","java flight recorder", "java"]
slug: "using-java-flight-recorder"
title: "Using Java FlightRecorder"
#series: ["Flight Recorder"]
#_build:
#  list: never
---




////
https://docs.oracle.com/en/java/javase/11/troubleshoot/diagnostic-tools.html[Official Troubleshooting guide for Java 11]

https://blogs.oracle.com/javamagazine/java-flight-recorder-and-jfr-event-streaming-in-java-14


https://daniel.mitterdorfer.name/talks/2017/Java%20Flight%20Recorder.pdf
https://www.dariawan.com/tutorials/java/java-11-flight-recorder-jep-328/

https://github.com/lhotari/jfr-report-tool

https://github.com/thegreystone/jmc-tutorial

.Talks
https://www.youtube.com/watch?v=E9K5m1HXMSc&list=WL&index=21&t=0s
https://www.youtube.com/watch?v=_69wTZR6lis&list=WL&index=22&t=0s
https://www.infoq.com/presentations/monitoring-jdk-jfr/[Continuous Monitoring with JDK Flight Recorder (JFR)]


http://hirt.se/blog/?p=1055[Solving Memory Leaks without Heap Dumps]

https://www.slideshare.net/PoonamBajaj5/jfr-174014342[CodeOne 2019 presentation on JFR]
https://www.slideshare.net/koduki/performance-monitoring-with-java-flight-recorder-on-openjdk-dev2406[Performance Monitoring with Java Flight Recorder on OpenJDK [DEV2406] ]



https://psy-lob-saw.blogspot.com/2016/02/why-most-sampling-java-profilers-are.html[Why (Most) Sampling Java Profilers Are Fucking Terrible]
https://psy-lob-saw.blogspot.com/2015/12/safepoints.html[Safepoints: Meaning, Side Effects and Overheads]
https://psy-lob-saw.blogspot.com/2016/06/the-pros-and-cons-of-agct.html[The Pros and Cons of AsyncGetCallTrace Profilers]
////


NOTE: This page assumes JDK 11, not JDK 8, that means there is no need to
`-XX:+UnlockCommercialFeatures`, `-XX:+FlightRecorder`. Or the use of
`-XX:+UnlockDiagnosticVMOptions` and `-XX:+DebugNonSafepoints` https://github.com/openjdk/jmc/blob/bacb448fd4ed1a9a5d887c50aebff4e854d3512a/core/org.openjdk.jmc.common/src/main/java/org/openjdk/jmc/common/version/JavaVersionSupport.java#L59-L60[source]

////
Cannot find public access to JDK-8036749, the only reference found by google is
https://bugs.openjdk.java.net/browse/JMC-6554
////

Also this article uses a lot the https://docs.oracle.com/en/java/javase/11/troubleshoot/environment-variables-and-system-properties.html#GUID-BE6E7B7F-A4BE-45C0-9078-AA8A66754B97[`JAVA_TOOL_OPTIONS`]
environment variable because most scenarios happens in a container.

== Introduction to Java Flight Recorder


.JFR big picture
image::/assets/jfr/java-flight-recorder-big-picture.svg[align="center"]




Before in Java 8 we needed to set specific commercial VM flags to unlock
FlightRecorder, this is not anymore necessary with Java 11.

Even if the flag is false it's possible to _start_ a JFR session.

So just checking the actual VM flags to make sure it's possible with the current VM
is not anymore necessary with Java 11.

[source, bash]
----
$ unset --unset JAVA_TOOL_OPTIONS jcmd $(pgrep java) VM.flags -all | grep FlightRecorder
     bool FlightRecorder                           = true                                      {product} {management}
    ccstr FlightRecorderOptions                    =                                           {product} {default}

----


To explore possible arguments, use the `help` command.

[source, bash]
----
$ env --unset JAVA_TOOL_OPTIONS jcmd $(pgrep java) help JFR.start
6:
JFR.start
Starts a new JFR recording

Impact: Medium: Depending on the settings for a recording, the impact can range from low to high.

Permission: java.lang.management.ManagementPermission(monitor)

Syntax : JFR.start [options]

Options: (options must be specified using the <key> or <key>=<value> syntax)
	name : [optional] Name that can be used to identify recording, e.g. \"My Recording\" (STRING, no default value)
	settings : [optional] Settings file(s), e.g. profile or default. See JRE_HOME/lib/jfr (STRING SET, no default value)
	delay : [optional] Delay recording start with (s)econds, (m)inutes), (h)ours), or (d)ays, e.g. 5h. (NANOTIME, 0)
	duration : [optional] Duration of recording in (s)econds, (m)inutes, (h)ours, or (d)ays, e.g. 300s. (NANOTIME, 0)
	disk : [optional] Recording should be persisted to disk (BOOLEAN, no default value)
	filename : [optional] Resulting recording filename, e.g. \"/home/user/My Recording.jfr\" (STRING, no default value)
	maxage : [optional] Maximum time to keep recorded data (on disk) in (s)econds, (m)inutes, (h)ours, or (d)ays, e.g. 60m, or 0 for no limit (NANOTIME, 0)
	maxsize : [optional] Maximum amount of bytes to keep (on disk) in (k)B, (M)B or (G)B, e.g. 500M, or 0 for no limit (MEMORY SIZE, 0)
	dumponexit : [optional] Dump running recording when JVM shuts down (BOOLEAN, no default value)
	path-to-gc-roots : [optional] Collect path to GC roots (BOOLEAN, false)
----


TODO look at `-XX:FlightRecorderOptions` options more specically, e.g. `stackdepth`, `maxchunksize`, `memorysize`, `repository`

[source]
----
jcmd 80657 help JFR.configure
80657:
JFR.configure
Configure JFR

Impact: Low

Permission: java.lang.management.ManagementPermission(monitor)

Syntax : JFR.configure [options]

Options: (options must be specified using the <key> or <key>=<value> syntax)
	repositorypath : [optional] Path to repository,.e.g \"My Repository\" (STRING, no default value)
	dumppath : [optional] Path to dump,.e.g \"My Dump path\" (STRING, no default value)
	stackdepth : [optional] Stack Depth (JULONG, 64)
	globalbuffercount : [optional] Number of global buffers, (JULONG, 20)
	globalbuffersize : [optional] Size of a global buffers, (MEMORY SIZE, 512k)
	thread_buffer_size : [optional] Size of a thread buffer (MEMORY SIZE, 8k)
	memorysize : [optional] Overall memory size,  (MEMORY SIZE, 10m)
	maxchunksize : [optional] Size of an individual disk chunk (MEMORY SIZE, 12m)
	samplethreads : [optional] Activate Thread sampling (BOOLEAN, true)
----


./usr/lib/jvm/java-11-amazon-corretto/lib/jfr/default.jfc
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>

<!--
     Recommended way to edit .jfc files is to use Java Mission Control,
     see Window -> Flight Recorder Template Manager.
-->

<configuration version="2.0" label="Continuous" description="Low overhead configuration safe for continuous use in production environments, typically less than 1 % overhead." provider="Oracle">

    <event name="jdk.ThreadAllocationStatistics">
      <setting name="enabled">true</setting>
      <setting name="period">everyChunk</setting>
    </event>

    <!-- a lot more event -->
</configuration>
----

With the `default` settings, the dumped file takes around 15mb for a 5min duration. With
this profile you'll get basic information on IO, GC events, simple method


./usr/lib/jvm/java-11-amazon-corretto/lib/jfr/profile.jfc
[source, xml]
----
<!--
     Recommended way to edit .jfc files is to use Java Mission Control,
     see Window -> Flight Recorder Template Manager.
-->

<configuration version="2.0" label="Profiling" description="Low overhead configuration for profiling, typically around 2 % overhead." provider="Oracle">

    <event name="jdk.ThreadAllocationStatistics">
      <setting name="enabled">true</setting>
      <setting name="period">everyChunk</setting>
    </event>

    <!-- a lot more event -->
</configuration>
----

With the `profile` settings, the dumped file takes around 35mb for a 5min duration.

It's also possible to create our own settings file and pass the absolute file path to the `settings` option.


[source, bash]
----
$ env --unset JAVA_TOOL_OPTIONS jcmd $(pgrep java) help JFR.dump
6:
JFR.dump
Copies contents of a JFR recording to file. Either the name or the recording id must be specified.

Impact: Low

Permission: java.lang.management.ManagementPermission(monitor)

Syntax : JFR.dump [options]

Options: (options must be specified using the <key> or <key>=<value> syntax)
	name : [optional] Recording name, e.g. \"My Recording\" (STRING, no default value)
	filename : [optional] Copy recording data to file, e.g. \"/home/user/My Recording.jfr\" (STRING, no default value)
	maxage : [optional] Maximum duration to dump, in (s)econds, (m)inutes, (h)ours, or (d)ays, e.g. 60m, or 0 for no limit (NANOTIME, 0)
	maxsize : [optional] Maximum amount of bytes to dump, in (M)B or (G)B, e.g. 500M, or 0 for no limit (MEMORY SIZE, 0)
	begin : [optional] Point in time to dump data from, e.g. 09:00, 21:35:00, 2018-06-03T18:12:56.827Z, 2018-06-03T20:13:46.832, -10m, -3h, or -1d (STRING, no default value)
	end : [optional] Point in time to dump data to, e.g. 09:00, 21:35:00, 2018-06-03T18:12:56.827Z, 2018-06-03T20:13:46.832, -10m, -3h, or -1d (STRING, no default value)
	path-to-gc-roots : [optional] Collect path to GC roots (BOOLEAN, false)
----

[source, bash]
----
env --unset JAVA_TOOL_OPTIONS jcmd $(pgrep java) help JFR.check
6:
JFR.check
Checks running JFR recording(s)

Impact: Low

Permission: java.lang.management.ManagementPermission(monitor)

Syntax : JFR.check [options]

Options: (options must be specified using the <key> or <key>=<value> syntax)
	name : [optional] Recording name, e.g. \"My Recording\" or omit to see all recordings (STRING, no default value)
	verbose : [optional] Print event settings for the recording(s) (BOOLEAN, false)
----

So what we would like to do is

[source, bash]
----
$ env --unset JAVA_TOOL_OPTIONS jcmd $(pgrep java) JFR.start name=app-profile duration=300s filename=/tmp/app-profile-$(date +%FT%H-%M-%S).jfr settings=profile
6:
Started recording 2. The result will be written to:

/tmp/app-profile-2020-03-26T16-41-48.jfr
----

Check if there's any recording at this time, they can be several.

[source, bash]
----
$ env --unset JAVA_TOOL_OPTIONS jcmd $(pgrep java) JFR.check
6:
Recording 2: name=app-profile duration=5m (running)
----

Also it's possible to stop manually any recording

[source, bash]
----
$ env --unset JAVA_TOOL_OPTIONS jcmd $(pgrep java) JFR.stop name=app-profile filename=/tmp/app-profile-$(date +%FT%H-%M-%S).jfr
----


Then get the file locally for analysis

[source, bash]
----
kubectl cp app-pod-579664d4f7-7dxsq:/tmp/app-profile-2020-03-26T16-57-14.jfr ./app-profile-2020-03-26T16-57-14.jfr --container=app-container
----

== JDK Mission Control
Then analyze the file in JDK Mission Control, (e.g. the one from `brew cask install jdk-mission-control`)


It's also possible to get very qui information using the `jfr` command line tool
(which is not always exported a symlink)

== Analyze with `jfr`

.events type histogram (summary)
[source, bash]
----
$ /usr/lib/jvm/java-11-amazon-corretto/bin/jfr summary /tmp/app-profile-2020-03-26T16-57-14.jfr

 Version: 2.0
 Chunks: 1
 Start: 2020-03-26 16:57:14 (UTC)
 Duration: 303 s

 Event Type                            Count  Size (bytes)
===========================================================
 jdk.ThreadPark                       130278       5868710
 jdk.SocketRead                        38804       1934842
 jdk.JavaMonitorWait                   38722       1378513
 jdk.NativeMethodSample                14702        263403
 jdk.ThreadCPULoad                     11821        271763
 jdk.ExecutionSample                    3010         54177
 jdk.ModuleExport                       2505         40187
 jdk.ClassLoaderStatistics              2344         72694
 jdk.ThreadAllocationStatistics          878         16962
 jdk.ModuleRequire                       754         11964
 jdk.BooleanFlag                         648         23106
 jdk.CPULoad                             298          7450
 jdk.JavaThreadStatistics                298          6258
 jdk.ClassLoadingStatistics              298          5066
 jdk.CompilerStatistics                  298         11324
 jdk.ExceptionStatistics                 298          6258
 jdk.ActiveSetting                       285         10497
 jdk.BiasedLockRevocation                275          7831
 jdk.NativeLibrary                       252         18564
 jdk.LongFlag                            229          8875
 jdk.UnsignedLongFlag                    182          7168
 jdk.InitialEnvironmentVariable          167         10243
 jdk.NetworkUtilization                  120          2640
 jdk.TenuringDistribution                 75          1437
 jdk.ThreadContextSwitchRate              30           510
 jdk.ThreadSleep                          29           696
 jdk.StringFlag                           26           880
 jdk.GCPhasePauseLevel2                   25          1080
 jdk.InitialSystemProperty                23          1316
 jdk.MetaspaceChunkFreeListSummary        20           520
 jdk.GCReferenceStatistics                20           350
 jdk.GCPhasePauseLevel1                   20           965
 jdk.CheckPoint                           17       1631868
 jdk.ExecuteVMOperation                   15           391
 jdk.DoubleFlag                           13           618
 jdk.BiasedLockClassRevocation            10           275
 jdk.GCHeapSummary                        10           475
 jdk.MetaspaceSummary                     10           580
 jdk.G1HeapSummary                        10           300
 jdk.OldObjectSample                      10           367
 jdk.UnsignedIntFlag                       8           300
 jdk.CodeCacheStatistics                   6           232
 jdk.ThreadStart                           6           102
 jdk.GarbageCollection                     5           145
 jdk.YoungGarbageCollection                5           100
 jdk.G1GarbageCollection                   5           100
 jdk.G1MMU                                 5           100
 jdk.EvacuationInformation                 5           185
 jdk.G1EvacuationYoungStatistics           5           160
 jdk.G1EvacuationOldStatistics             5           152
 jdk.G1BasicIHOP                           5           243
 jdk.G1AdaptiveIHOP                        5           240
 jdk.GCPhasePause                          5           150
 jdk.IntFlag                               3           107
 jdk.BiasedLockSelfRevocation              2            45
 jdk.PhysicalMemory                        2            46
 jdk.ThreadDump                            2       1389568
 jdk.CodeSweeperStatistics                 2            64
 jdk.GCConfiguration                       2            60
 jdk.ThreadEnd                             1            17
 jdk.Metadata                              1         74738
 jdk.JavaMonitorEnter                      1            33
 jdk.SafepointBegin                        1            24
 jdk.JVMInformation                        1           898
 jdk.OSInformation                         1           367
 jdk.VirtualizationInformation             1            33
 jdk.CPUInformation                        1          1432
 jdk.CPUTimeStampCounter                   1            25
 jdk.CompilerConfiguration                 1            15
 jdk.CodeCacheConfiguration                1            51
 jdk.CodeSweeperConfiguration              1            15
 jdk.GCSurvivorConfiguration               1            15
 jdk.GCTLABConfiguration                   1            17
 jdk.GCHeapConfiguration                   1            31
 jdk.YoungGenerationConfiguration          1            22
 jdk.ActiveRecording                       1            87
 jdk.JavaMonitorInflate                    0             0
 jdk.ReservedStackActivation               0             0
 jdk.ClassLoad                             0             0
 jdk.ClassDefine                           0             0
 jdk.ClassUnload                           0             0
 jdk.IntFlagChanged                        0             0
 jdk.UnsignedIntFlagChanged                0             0
 jdk.LongFlagChanged                       0             0
 jdk.UnsignedLongFlagChanged               0             0
 jdk.DoubleFlagChanged                     0             0
 jdk.BooleanFlagChanged                    0             0
 jdk.StringFlagChanged                     0             0
 jdk.MetaspaceGCThreshold                  0             0
 jdk.MetaspaceAllocationFailure            0             0
 jdk.MetaspaceOOM                          0             0
 jdk.PSHeapSummary                         0             0
 jdk.ParallelOldGarbageCollection          0             0
 jdk.OldGarbageCollection                  0             0
 jdk.ObjectCountAfterGC                    0             0
 jdk.PromoteObjectInNewPLAB                0             0
 jdk.PromoteObjectOutsidePLAB              0             0
 jdk.PromotionFailed                       0             0
 jdk.EvacuationFailed                      0             0
 jdk.ConcurrentModeFailure                 0             0
 jdk.GCPhasePauseLevel3                    0             0
 jdk.GCPhasePauseLevel4                    0             0
 jdk.GCPhaseConcurrent                     0             0
 jdk.AllocationRequiringGC                 0             0
 jdk.G1HeapRegionTypeChange                0             0
 jdk.Compilation                           0             0
 jdk.CompilerPhase                         0             0
 jdk.CompilationFailure                    0             0
 jdk.CompilerInlining                      0             0
 jdk.SweepCodeCache                        0             0
 jdk.CodeCacheFull                         0             0
 jdk.SafepointStateSynchronization         0             0
 jdk.SafepointWaitBlocked                  0             0
 jdk.SafepointCleanup                      0             0
 jdk.SafepointCleanupTask                  0             0
 jdk.SafepointEnd                          0             0
 jdk.Shutdown                              0             0
 jdk.ObjectAllocationInNewTLAB             0             0
 jdk.ObjectAllocationOutsideTLAB           0             0
 jdk.DumpReason                            0             0
 jdk.DataLoss                              0             0
 jdk.SystemProcess                         0             0
 jdk.X509Validation                        0             0
 jdk.ObjectCount                           0             0
 jdk.G1HeapRegionInformation               0             0
 jdk.ZPageAllocation                       0             0
 jdk.ZThreadPhase                          0             0
 jdk.ZStatisticsCounter                    0             0
 jdk.ZStatisticsSampler                    0             0
 jdk.FileForce                             0             0
 jdk.FileRead                              0             0
 jdk.FileWrite                             0             0
 jdk.SocketWrite                           0             0
 jdk.JavaExceptionThrow                    0             0
 jdk.JavaErrorThrow                        0             0
 jdk.SecurityPropertyModification          0             0
 jdk.X509Certificate                       0             0
 jdk.TLSHandshake                          0             0
----


== Inspect with JDK Mission Control

https://docs.oracle.com/en/java/javase/11/troubleshoot/diagnostic-tools.html#GUID-7E8058D0-249E-44DB-8714-3AA9DA6A4DB8

=== Memory LEaks

https://docs.oracle.com/en/java/javase/11/troubleshoot/troubleshoot-memory-leaks.html#GUID-8090B138-6E0C-4926-9659-BE739062AB75

=== Performance Issues

https://docs.oracle.com/en/java/javase/11/troubleshoot/troubleshoot-performance-issues-using-jfr.html#GUID-0FE29092-18B5-4BEB-8D8D-0CBA7A4FEA1D


// TODO options of -XX:StartFlightRecording, see https://www.dariawan.com/tutorials/java/java-11-flight-recorder-jep-328/
Finding the options

Un practical to have meaningful help from the usual
`java -XX:+UnlockDiagnosticVMOptions -XX:+UnlockExperimentalVMOptions -XX:+PrintFlagsFinal -version`, I found that
using `jcmd` to be quite useful to help me pass arguments to `-XX:StartFlightRecording`.

[source]
----
❯ jcmd 90091 VM.version
90091:
OpenJDK 64-Bit Server VM version 11.0.7+10-LTS
JDK 11.0.7
❯ jcmd 90091 help JFR.start
90091:
JFR.start
Starts a new JFR recording

Impact: Medium: Depending on the settings for a recording, the impact can range from low to high.

Permission: java.lang.management.ManagementPermission(monitor)

Syntax : JFR.start [options]

Options: (options must be specified using the <key> or <key>=<value> syntax)
       name : [optional] Name that can be used to identify recording, e.g. \"My Recording\" (STRING, no default value)
       settings : [optional] Settings file(s), e.g. profile or default. See JRE_HOME/lib/jfr (STRING SET, no default value)
       delay : [optional] Delay recording start with (s)econds, (m)inutes), (h)ours), or (d)ays, e.g. 5h. (NANOTIME, 0)
       duration : [optional] Duration of recording in (s)econds, (m)inutes, (h)ours, or (d)ays, e.g. 300s. (NANOTIME, 0)
       disk : [optional] Recording should be persisted to disk (BOOLEAN, no default value)
       filename : [optional] Resulting recording filename, e.g. \"/Users/user/My Recording.jfr\" (STRING, no default value)
       maxage : [optional] Maximum time to keep recorded data (on disk) in (s)econds, (m)inutes, (h)ours, or (d)ays, e.g. 60m, or 0 for no limit (NANOTIME, 0)
       maxsize : [optional] Maximum amount of bytes to keep (on disk) in (k)B, (M)B or (G)B, e.g. 500M, or 0 for no limit (MEMORY SIZE, 0)
       dumponexit : [optional] Dump running recording when JVM shuts down (BOOLEAN, no default value)
       path-to-gc-roots : [optional] Collect path to GC roots (BOOLEAN, false)
----



=== Profile startup

.Time bound profiling at JVM startup (https://github.com/openjdk/jmc/blob/a07f3a28e65993909f6281ca5617f0ecc2b152a9/application/org.openjdk.jmc.ide.launch/src/main/java/org/openjdk/jmc/ide/launch/model/JfrArgsBuilder.java#L65[source])
[source]
----
-XX:StartFlightRecording=settings=profile,delay=20s,duration=60s,name=app-startup,filename=/app-startup.jfr
----

.In the container, checking JFR
[source]
----
❯ env --unset JAVA_TOOL_OPTIONS jcmd $(pgrep java) JFR.check
6:
Recording 1: name=app-startup duration=60s (running) <1>
❯ env --unset JAVA_TOOL_OPTIONS jcmd $(pgrep java) JFR.check
6:
No available recordings.

Use jcmd 6 JFR.start to start a recording. <2>
❯ ls -lah
-rw-r--r--   1 root root 3.3M May  6 22:35 rec.jfr
----
<1> Indicates the configured 30s recording is ongoing.
<2> No more recording once the duration is over.

=== Profile post-startup

.Delayed and time bound profiling at JVM startup (https://github.com/openjdk/jmc/blob/a07f3a28e65993909f6281ca5617f0ecc2b152a9/application/org.openjdk.jmc.ide.launch/src/main/java/org/openjdk/jmc/ide/launch/model/JfrArgsBuilder.java#L65[source])
[source]
----
-XX:StartFlightRecording=settings=profile,delay=20s,duration=60s,name=post-startup,filename=/post-startup.jfr
----

.In the container, checking JFR
[source]
----
❯ env --unset JAVA_TOOL_OPTIONS jcmd $(pgrep java) JFR.check
6:
Recording 1: name=post-startup duration=60s (delayed) <1>
❯ env --unset JAVA_TOOL_OPTIONS jcmd $(pgrep java) JFR.check
6:
Recording 1: name=app-startup duration=60s (running) <2>
❯ env --unset JAVA_TOOL_OPTIONS jcmd $(pgrep java) JFR.check
6:
No available recordings.

Use jcmd 6 JFR.start to start a recording. <3>
❯ ls -lah
-rw-r--r--   1 root root 3.3M May  6 22:35 rec.jfr
----
<1> Indicates there's a recording that will start at some point in the future.
<2> Indicates the configured 30s recording is ongoing.
<3> No more recording once the duration is over.


=== Continuous profiling


Started recording 1. No limit specified, using maxsize=250MB as default.


.Delayed and time bound profiling at JVM startup (https://github.com/openjdk/jmc/blob/a07f3a28e65993909f6281ca5617f0ecc2b152a9/application/org.openjdk.jmc.ide.launch/src/main/java/org/openjdk/jmc/ide/launch/model/JfrArgsBuilder.java#L65[source])
[source]
----
-XX:StartFlightRecording=settings=profile,delay=20s,maxage=30s,name=post-startup,filename=post-startup.jfr
----

This would create a rolling buffer of 30 seconds duration. There is no stipulation on how big this file could get,
unless the maxsize option is set the default is `maxsize=250MB`.

.In the container, checking JFR
[source]
----
❯ env --unset JAVA_TOOL_OPTIONS jcmd $(pgrep java) JFR.check
6:
Recording 1: name=post-startup duration=60s (delayed) <1>
❯ env --unset JAVA_TOOL_OPTIONS jcmd $(pgrep java) JFR.check
6:
Recording 1: name=app-startup duration=60s (running) <2>
❯ env --unset JAVA_TOOL_OPTIONS jcmd $(pgrep java) JFR.check
6:
No available recordings.

Use jcmd 6 JFR.start to start a recording. <3>
❯ ls -lah
-rw-r--r--   1 root root 3.3M May  6 22:35 rec.jfr
----
<1> Indicates there's a recording that will start at some point in the future.
<2> Indicates the configured 30s recording is ongoing.
<3> No more recording once the duration is over.

=== Profiling the startup then profile continuously

.Start to recording
[source]
----
-XX:StartFlightRecording=duration=30s,settings=profile,name=app-startup,filename=app-startup.jfr \
-XX:StartFlightRecording=delay=31s,maxsize=100mb,settings=profile,name=continuous,filename=continuous.jfr
----




=== Notes from JMC

// TODO help page from jdk mission control (JMC) ?

> Could not find a usable recording running in the JVM! You can get an automatically started
> continuous flight recording by using the JVM option `-XX:FlightRecorderOptions=defaultrecording=true`
> (also requires the options `-XX:+UnlockCommercialFeatures` `-XX:+FlightRecorder`).

// TODO commercial options not anymore

.JMC Help - § Managing Flight Recording Templates
====
1. Right-click a JVM in the JVM Browser and select Start Flight Recording
2. Click Template Manager in the Start Flight Recording Wizard.
JFR includes two pre-configured server-side recording templates:

** Continuous: A pre-configured template for continuous use in production environments with less than one percent overhead. This template is used for the default recording
** Profiling: A pre-configured template for profiling with around two percent overhead.
====

menu:JVM Browser>[Select a JVM>Start Flight Recording]

And from the _Start Flight Recording_ window, you can select configurations.

menu:Start Flight Recording[Event Settings]

At this time two configurations by default should appear.

* "Continuous _on server_"
* "Profiling _on server_"

I'm not sure yet but I believe the _on server_ mention means those are taken from the JVM shipped configurations
mentioned above, plus the description and label are similar.

* _Continuous_ refer to the `$JAVA_HOME/lib/jfr/default.jfc` (~1% overhead)
* _Profiling_ refer to the `$JAVA_HOME/lib/jfr/profile.jfc` (~2% overhead)

And anyway if these do not match your need it's possible to use your own configuration (`.jfc` files)
and manage them with the "_template manager_"

menu:Window[Flight Recoding Template Manager]



https://github.com/openjdk/jmc/blob/a07f3a28e65993909f6281ca5617f0ecc2b152a9/application/org.openjdk.jmc.ide.launch/src/main/java/org/openjdk/jmc/ide/launch/model/JfrArgsBuilder.java


== Memory Leak

Old Object Sample Event added in JDK 10 to profile memory leak, http://hirt.se/blog/?p=1055[blog from Marcus Hirt]

[source]
----
-XX:StartFlightRecording=settings=profile,path-to-gc-roots=true,...
----

.Difference in stacktrace setting
[source]
----
❯ cat ~/.asdf/installs/java/amazon-corretto-11.0.7.10.1/lib/jfr/profile.jfc | grep -A5 OldObjectSample
    <event name="jdk.OldObjectSample">
      <setting name="enabled" control="memory-leak-detection-enabled">true</setting>
      <setting name="stackTrace" control="memory-leak-detection-stack-trace">true</setting>
      <setting name="cutoff" control="memory-leak-detection-cutoff">0 ns</setting>
    </event>

❯ cat ~/.asdf/installs/java/amazon-corretto-11.0.7.10.1/lib/jfr/default.jfc | grep -A5 OldObjectSample
    <event name="jdk.OldObjectSample">
      <setting name="enabled" control="memory-leak-detection-enabled">true</setting>
      <setting name="stackTrace" control="memory-leak-detection-stack-trace">false</setting>
      <setting name="cutoff" control="memory-leak-detection-cutoff">0 ns</setting>
    </event>

----



=== Dump on exit

1. VM Crash => `hs_err<pid>.jfr`
2. OOM => `hs_oom<pid>.jfr`

add these options `dumponexit=true`, and override the filename if the above arent suited `dumponexitpath=/vm-exit.jfr`

.jfrOptionSet.cpp
[source]
----
static const ObsoleteOption OBSOLETE_OPTIONS[] = {
  {"checkpointbuffersize", ""},
  {"maxsize",              "Use -XX:StartFlightRecording=maxsize=... instead."},
  {"maxage",               "Use -XX:StartFlightRecording=maxage=... instead."},
  {"settings",             "Use -XX:StartFlightRecording=settings=... instead."},
  {"defaultrecording",     "Use -XX:StartFlightRecording=disk=false to create an in-memory recording."},
  {"disk",                 "Use -XX:StartFlightRecording=disk=... instead."},
  {"dumponexit",           "Use -XX:StartFlightRecording=dumponexit=... instead."},
  {"dumponexitpath",       "Use -XX:StartFlightRecording=filename=... instead."},
  {"loglevel",             "Use -Xlog:jfr=... instead."}
};
----


[source]
----
-Xlog:jfr
----



env --unset JAVA_TOOL_OPTIONS jcmd $(pidof java) JFR.start name=app-profile path-to-gc-roots=true maxsize=200mb settings=profile name=continuous-profile stackdepth=128 disk=true dumponexit=true filename=/gclogs/app-profile-$(date +%FT%H-%M-%S).jfr
env --unset JAVA_TOOL_OPTIONS jcmd $(pidof java) JFR.dump filename=/gclogs/hotspot-pid-6-2020_05_28_11_13_52.jfr



[source]
----
$ env --unset JAVA_TOOL_OPTIONS jcmd $(pidof java) VM.native_memory
6:

Native Memory Tracking:

Total: reserved=5324939KB, committed=3600539KB
-                 Java Heap (reserved=2793472KB, committed=2793472KB)
                            (mmap: reserved=2793472KB, committed=2793472KB)

-                     Class (reserved=1202747KB, committed=174583KB)
                            (classes #30836)
                            (  instance classes #28978, array classes #1858)
                            (malloc=6715KB #103633)
                            (mmap: reserved=1196032KB, committed=167868KB)
                            (  Metadata:   )
                            (    reserved=147456KB, committed=145988KB)
                            (    used=141426KB)
                            (    free=4562KB)
                            (    waste=0KB =0.00%)
                            (  Class space:)
                            (    reserved=1048576KB, committed=21880KB)
                            (    used=19330KB)
                            (    free=2550KB)
                            (    waste=0KB =0.00%)

-                    Thread (reserved=636185KB, committed=93205KB)
                            (thread #616)
                            (stack: reserved=633176KB, committed=90196KB)
                            (malloc=2222KB #3697)
                            (arena=787KB #1231)

-                      Code (reserved=255120KB, committed=101864KB)
                            (malloc=7432KB #29664)
                            (mmap: reserved=247688KB, committed=94432KB)

-                        GC (reserved=166886KB, committed=166886KB)
                            (malloc=29750KB #67554)
                            (mmap: reserved=137136KB, committed=137136KB)

-                  Compiler (reserved=4913KB, committed=4913KB)
                            (malloc=4847KB #2888)
                            (arena=66KB #5)

-                  Internal (reserved=9799KB, committed=9799KB)
                            (malloc=9799KB #16775)

-                     Other (reserved=135800KB, committed=135800KB)
                            (malloc=135800KB #552)

-                    Symbol (reserved=30719KB, committed=30719KB)
                            (malloc=25916KB #330226)
                            (arena=4803KB #1)

-    Native Memory Tracking (reserved=10409KB, committed=10409KB)
                            (malloc=108KB #1385)
                            (tracking overhead=10300KB)

-               Arena Chunk (reserved=217KB, committed=217KB)
                            (malloc=217KB)

-                   Tracing (reserved=75866KB, committed=75866KB)
                            (malloc=75866KB #85438)

-                   Logging (reserved=7KB, committed=7KB)
                            (malloc=7KB #269)

-                 Arguments (reserved=18KB, committed=18KB)
                            (malloc=18KB #507)

-                    Module (reserved=1856KB, committed=1856KB)
                            (malloc=1856KB #7920)

-              Synchronizer (reserved=885KB, committed=885KB)
                            (malloc=885KB #7308)

-                 Safepoint (reserved=8KB, committed=8KB)
                            (mmap: reserved=8KB, committed=8KB)

-                   Unknown (reserved=32KB, committed=32KB)
                            (mmap: reserved=32KB, committed=32KB)

----



== Startup latencies issues


== Controlling JFR programmatically

While JDK 14 allows to consume events on the fly, previous JDK versions (from JDK 11)
offer a public API to control Flight Recorder programmatically.

[source, java]
----
Configuration c = Configuration.getConfiguration("profile");
Recording r = new Recording(c);
r.setName("contunuous jaxrs");
r.enable(JaxRsIncovation.class);
r.setMaxAge(Duration.of(...));
r.start();
...
r.stop();
r.dump(Files.createTempFile("my-jaxrs", ".jfr"));
----